### ISSUE TITLE
IPFS Desktop Fails

### ISSUE THREAD

**Issue by lsji07** [ipfs-shipyard/ipfs-desktop#1013]
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.7.3
- **Electron Version**: 4.0.8
- **Chrome Version**: 69.0.3497.128

**Error**

```
Error: Object has been destroyed
    at ctx.launchWebUI (C:\Users\leigh\AppData\Local\Programs\ipfs-desktop\resources\app.asar\out\late\webui\index.js:92:22)
    at click (C:\Users\leigh\AppData\Local\Programs\ipfs-desktop\resources\app.asar\out\late\tray.js:65:7)
    at MenuItem.click (C:\Users\leigh\AppData\Local\Programs\ipfs-desktop\resources\electron.asar\browser\api\menu-item.js:56:9)
    at Function.executeCommand (C:\Users\leigh\AppData\Local\Programs\ipfs-desktop\resources\electron.asar\browser\api\menu.js:31:13)
```

**Comment by hacdias** [comment]
Hey @lsji07! Please upgrade to the latest version: https://github.com/ipfs-shipyard/ipfs-desktop/releases/tag/v0.8.0
