### ISSUE TITLE
Command failed: powershell

### ISSUE THREAD

**Issue by KK-OS** [ipfs-shipyard/ipfs-desktop#1014]
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.8.0
- **Electron Version**: 5.0.2
- **Chrome Version**: 73.0.3683.121

**Error**

```
Error: Command failed: powershell.exe -nop -exec bypass -win hidden

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:194:13)
    at maybeClose (internal/child_process.js:998:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
```

**Comment by hacdias** [comment]
Hey @KK-OS! Thanks for the report. What were you doing when that happened?

**Comment by hacdias** [comment]
I'm closing due to the lack of information. You can re-open this if it happens again, with more information.
