### ISSUE TITLE
Error with space in home folder

### ISSUE THREAD

**Issue by Coder-256** [ipfs-shipyard/ipfs-desktop#1049]
Literally all I did was install IPFS desktop and was immediately greeted with this error.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.8.0
- **Electron Version**: 5.0.2
- **Chrome Version**: 73.0.3683.121

**Error**

```
Error: Command failed: powershell.exe -nop -exec bypass -win hidden C:\Users\Jacob Greenfield\AppData\Local\Programs\ipfs-desktop\resources\app.asar.unpacked\out\late\ipfs-on-path\scripts\install.ps1
C:\Users\Jacob : The term 'C:\Users\Jacob' is not recognized as the name of a cmdlet, function, script file, or 
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try 
again.
At line:1 char:1
  C:\Users\Jacob Greenfield\AppData\Local\Programs\ipfs-desktop\resourc ...
  ~~~~~~~~~~~~~~
      CategoryInfo          : ObjectNotFound: (C:\Users\Jacob:String) [], CommandNotFoundException
      FullyQualifiedErrorId : CommandNotFoundException
 

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:194:13)
    at maybeClose (internal/child_process.js:998:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
```

**Comment by Coder-256** [comment]
Oops this might be a duplicate of #964... I'll try installing 0.9

**Comment by Coder-256** [comment]
0.9 fixed it.
