### ISSUE TITLE
Error launching 0.9.0-beta.2

### ISSUE THREAD

**Issue by momack2** [ipfs-shipyard/ipfs-desktop#1077]
Please describe what you were doing when this error happened: I tried to launch the beta as requested by @hacdias to debug setting the "launch on startup" checkbox - https://github.com/ipfs-shipyard/ipfs-desktop/issues/1066

**Specifications**

- **OS**: darwin
- **IPFS Desktop Version**: 0.9.0-beta.2
- **Electron Version**: 6.0.2
- **Chrome Version**: 76.0.3809.110

**Error**

```
Error: EROFS: read-only file system, open '/private/var/folders/pf/43th2gq17rd5ft2_2wn05mhc0000gn/T/AppTranslocation/EF5C9B25-0696-4902-BA7F-C474CBD0A59A/d/IPFS Desktop.app/Contents/Resources/app.asar.unpacked/out/ipfs-on-path/scripts/IPFS_PATH'
    at Object.openSync (fs.js:447:3)
    at Object.func (electron/js2c/asar.js:155:31)
    at Object.func [as openSync] (electron/js2c/asar.js:155:31)
    at Object.writeFileSync (fs.js:1206:35)
    at writeIpfsPath (/private/var/folders/pf/43th2gq17rd5ft2_2wn05mhc0000gn/T/AppTranslocation/EF5C9B25-0696-4902-BA7F-C474CBD0A59A/d/IPFS Desktop.app/Contents/Resources/app.asar/out/daemon/index.js:376:23)
    at _callee3$ (/private/var/folders/pf/43th2gq17rd5ft2_2wn05mhc0000gn/T/AppTranslocation/EF5C9B25-0696-4902-BA7F-C474CBD0A59A/d/IPFS Desktop.app/Contents/Resources/app.asar/out/daemon/index.js:163:27)
    at tryCatch (/private/var/folders/pf/43th2gq17rd5ft2_2wn05mhc0000gn/T/AppTranslocation/EF5C9B25-0696-4902-BA7F-C474CBD0A59A/d/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/private/var/folders/pf/43th2gq17rd5ft2_2wn05mhc0000gn/T/AppTranslocation/EF5C9B25-0696-4902-BA7F-C474CBD0A59A/d/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.<computed> [as next] (/private/var/folders/pf/43th2gq17rd5ft2_2wn05mhc0000gn/T/AppTranslocation/EF5C9B25-0696-4902-BA7F-C474CBD0A59A/d/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/private/var/folders/pf/43th2gq17rd5ft2_2wn05mhc0000gn/T/AppTranslocation/EF5C9B25-0696-4902-BA7F-C474CBD0A59A/d/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
```

**Comment by hacdias** [comment]
Uh, do you have any special/non-default security settings enabled? The problem stated shouldn't happen to the regular user... It seems you have apps installed on a read-only file system, and since we use the file system to store some data, it fails.

**Comment by hacdias** [comment]
Okay, I have updates. Good and bad. Found this info:

> Starting with macOS Sierra, running a newly-downloaded app from a disk image, archive, or the Downloads directory will cause Gatekeeper to isolate that app at a unspecified read-only location in the filesystem. This will prevent the app from accessing code or content using relative paths.

Did you run it inside the DMG itself? I can reproduce the exact same error if you did so, which is great! Please let me know if that was it before thinking about a solution (which I actually... have).

**Comment by momack2** [comment]
I used the "IPFS-Desktop-0.9.0-beta.2-mac.zip" option before. Trying "IPFS-Desktop-0.9.0-beta.2.dmg" quits on startup with the same notification. Will "report the error" for that as well in case there are any differences - https://github.com/ipfs-shipyard/ipfs-desktop/issues/1078.

Yes, it does error on startup and prevents execution.

**Comment by andrew** [comment]
I tried downloading the zip of 0.10.2 this morning and couldn't get it working at all, but the DMG version did work once I got past https://github.com/ipfs-shipyard/ipfs-desktop/issues/1211#issuecomment-576683161
