### ISSUE TITLE
Error for IPFS-Desktop-0.9.0-beta.2.dmg quitting on startup

### ISSUE THREAD

**Issue by momack2** [ipfs-shipyard/ipfs-desktop#1078]
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: darwin
- **IPFS Desktop Version**: 0.9.0-beta.2
- **Electron Version**: 6.0.2
- **Chrome Version**: 76.0.3809.110

**Error**

```
Error: EROFS: read-only file system, open '/private/var/folders/pf/43th2gq17rd5ft2_2wn05mhc0000gn/T/AppTranslocation/CBBA83D5-FF72-4850-8C10-ABDCFC1DFE3F/d/IPFS Desktop.app/Contents/Resources/app.asar.unpacked/out/ipfs-on-path/scripts/IPFS_PATH'
    at Object.openSync (fs.js:447:3)
    at Object.func (electron/js2c/asar.js:155:31)
    at Object.func [as openSync] (electron/js2c/asar.js:155:31)
    at Object.writeFileSync (fs.js:1206:35)
    at writeIpfsPath (/private/var/folders/pf/43th2gq17rd5ft2_2wn05mhc0000gn/T/AppTranslocation/CBBA83D5-FF72-4850-8C10-ABDCFC1DFE3F/d/IPFS Desktop.app/Contents/Resources/app.asar/out/daemon/index.js:376:23)
    at _callee3$ (/private/var/folders/pf/43th2gq17rd5ft2_2wn05mhc0000gn/T/AppTranslocation/CBBA83D5-FF72-4850-8C10-ABDCFC1DFE3F/d/IPFS Desktop.app/Contents/Resources/app.asar/out/daemon/index.js:163:27)
    at tryCatch (/private/var/folders/pf/43th2gq17rd5ft2_2wn05mhc0000gn/T/AppTranslocation/CBBA83D5-FF72-4850-8C10-ABDCFC1DFE3F/d/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/private/var/folders/pf/43th2gq17rd5ft2_2wn05mhc0000gn/T/AppTranslocation/CBBA83D5-FF72-4850-8C10-ABDCFC1DFE3F/d/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.<computed> [as next] (/private/var/folders/pf/43th2gq17rd5ft2_2wn05mhc0000gn/T/AppTranslocation/CBBA83D5-FF72-4850-8C10-ABDCFC1DFE3F/d/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/private/var/folders/pf/43th2gq17rd5ft2_2wn05mhc0000gn/T/AppTranslocation/CBBA83D5-FF72-4850-8C10-ABDCFC1DFE3F/d/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
```

**Comment by hacdias** [comment]
Closing this as this is the same as #1077
