### ISSUE TITLE
Freshly downloaded appImage fails to start

### ISSUE THREAD

**Issue by kaotisk-hund** [ipfs-shipyard/ipfs-desktop#1087]
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: linux
- **IPFS Desktop Version**: 0.9.0-beta.3
- **Electron Version**: 6.0.7
- **Chrome Version**: 76.0.3809.139

**Error**

```
Error: EROFS: read-only file system, open '/tmp/.mount_ipfs-d5tPRH7/resources/app.asar.unpacked/out/ipfs-on-path/scripts/IPFS_PATH'
    at Object.openSync (fs.js:447:3)
    at Object.func (electron/js2c/asar.js:155:31)
    at Object.func [as openSync] (electron/js2c/asar.js:155:31)
    at Object.writeFileSync (fs.js:1206:35)
    at writeIpfsPath (/tmp/.mount_ipfs-d5tPRH7/resources/app.asar/out/daemon/index.js:376:23)
    at _callee3$ (/tmp/.mount_ipfs-d5tPRH7/resources/app.asar/out/daemon/index.js:163:27)
    at tryCatch (/tmp/.mount_ipfs-d5tPRH7/resources/app.asar/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/tmp/.mount_ipfs-d5tPRH7/resources/app.asar/node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.<computed> [as next] (/tmp/.mount_ipfs-d5tPRH7/resources/app.asar/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/tmp/.mount_ipfs-d5tPRH7/resources/app.asar/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
```

**Comment by hacdias** [comment]
Hey @kaotisk-hund! Thanks. That specific error was fixed on #1079 😃 I'm releasing 0.9.0
