### ISSUE TITLE
安装了desktop，打不开

### ISSUE THREAD

**Issue by Verfen** [ipfs-shipyard/ipfs-desktop#1111]
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.8.0
- **Electron Version**: 5.0.2
- **Chrome Version**: 73.0.3683.121

**Error**

```
Error: EPERM: operation not permitted, open 'C:\Program Files\HPIPS\HPIPS Browser\IPFSREPO\config'
    at Object.openSync (fs.js:453:3)
    at Object.func [as openSync] (electron/js2c/asar.js:155:31)
    at Object.writeFileSync (fs.js:1246:35)
    at Object.writeFileSync (C:\Users\WIN10\AppData\Local\Programs\ipse-desktop\resources\app.asar\node_modules\jsonfile\index.js:117:13)
    at writeConfigFile (C:\Users\WIN10\AppData\Local\Programs\ipse-desktop\resources\app.asar\out\utils\ipse-peers.js:37:23)
    at _callee2$ (C:\Users\WIN10\AppData\Local\Programs\ipse-desktop\resources\app.asar\out\utils\ipse-peers.js:214:15)
    at tryCatch (C:\Users\WIN10\AppData\Local\Programs\ipse-desktop\resources\app.asar\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (C:\Users\WIN10\AppData\Local\Programs\ipse-desktop\resources\app.asar\node_modules\regenerator-runtime\runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\WIN10\AppData\Local\Programs\ipse-desktop\resources\app.asar\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (C:\Users\WIN10\AppData\Local\Programs\ipse-desktop\resources\app.asar\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\WIN10\AppData\Local\Programs\ipse-desktop\resources\app.asar\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
```

**Comment by hacdias** [comment]
Hello, I'm closing this. If you get this error in the future, please let me know so we can address thi again.
