### ISSUE TITLE
Error : Cannot read property 'trySudo'

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [ipfs-shipyard/ipfs-desktop#1113]
Please describe what you were doing when this error happened.
This happen when trying to activate the ¨add IPFS to the command line¨ setting from a launched IPFS-desktop.
**Specifications**

- **OS**: linux
- **IPFS Desktop Version**: 0.9.1
- **Electron Version**: 6.0.7
- **Chrome Version**: 76.0.3809.139
```
            .-/+oossssoo+/-. 
        `:+ssssssssssssssssss+:` 
      -+ssssssssssssssssssyyssss+- 
    .ossssssssssssssssssdMMMNysssso.       pm@Velvet4Renaissance 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      --------------------- 
  +ssssssssshmydMMMMMMMNddddyssssssss+     OS: Ubuntu 18.04.3 LTS x86_64 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Host: MS-7918 1.0 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Kernel: 4.15.0-62-lowlatency 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Uptime: 4 mins 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   Packages: 3130 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   Shell: bash 4.4.20 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 3440x1440 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   DE: Deepin 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    WM: Mutter(DeepinGala) 
  +sssssssssdmydMMMMMMMMddddyssssssss+     Theme: Deepin [GTK2/3] 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      Icons: Deepin [GTK2/3] 
    .ossssssssssssssssssdMMMNysssso.       Terminal: deepin-terminal 
      -+sssssssssssssssssyyyssss+-         Terminal Font: Noto Mono 11 
        `:+ssssssssssssssssss+:`           CPU: Intel i7-4790 (8) @ 4.000GHz 
            .-/+oossssoo+/-.               GPU: NVIDIA GeForce GTX 1060 6GB 
                                           Memory: 1905MiB / 32111MiB
```
(That´s more precisely, Ubuntu studio, due to the lowlatency kernel)
**Error**

```
TypeError: Cannot read property 'trySudo' of undefined
    at _callee5$ (/opt/IPFS Desktop/resources/app.asar/out/ipfs-on-path/index.js:212:35)
    at tryCatch (/opt/IPFS Desktop/resources/app.asar/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/opt/IPFS Desktop/resources/app.asar/node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.<computed> [as next] (/opt/IPFS Desktop/resources/app.asar/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/opt/IPFS Desktop/resources/app.asar/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/opt/IPFS Desktop/resources/app.asar/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at /opt/IPFS Desktop/resources/app.asar/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at /opt/IPFS Desktop/resources/app.asar/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12
    at run (/opt/IPFS Desktop/resources/app.asar/out/ipfs-on-path/index.js:199:15)
```

**Comment by hacdias** [comment]
Thank you!
