### ISSUE TITLE
Unable to run AppImage

### ISSUE THREAD

**Issue by ibnesayeed** [ipfs-shipyard/ipfs-desktop#1136]
```
$ sudo chmod a+x /tmp/ipfs-desktop-0.9.2-linux-x86_64.AppImage
[sudo] password for user:             
$ /tmp/ipfs-desktop-0.9.2-linux-x86_64.AppImage
2019-09-19T17:22:00.670Z info: [meta] logs can be found on /home/user/.config/IPFS Desktop
Checking for update
Generated new staging user ID: fb147aa0-c32f-1c04-a841-62014fc58725
Update for version 0.9.2 is not available (latest version: 0.9.2, downgrade is disallowed).
2019-09-19T17:22:03.214Z info: [web ui] window ready
2019-09-19T17:22:03.214Z info: [tray] starting
2019-09-19T17:22:03.268Z info: [tray] started
2019-09-19T17:22:03.269Z info: [ipfsd] start daemon STARTED
2019-09-19T17:22:06.859Z info: [ipfsd] start daemon FINISHED 3.589443045139313s
2019-09-19T17:22:06.932Z info: [launch on startup] disabled
2019-09-19T17:22:07.134Z info: [ipfs on path] no-sudo: stderr: fs.js:126
    throw err;
    ^

Error: EACCES: permission denied, symlink '/tmp/.mount_ipfs-dxBTGy9/resources/app.asar.unpacked/out/ipfs-on-path/scripts/ipfs.sh' -> '/usr/local/bin/ipfs'
    at Object.symlinkSync (fs.js:935:3)
    at Object.createSymlinkSync (/tmp/.mount_ipfs-dxBTGy9/resources/app.asar/node_modules/fs-extra/lib/ensure/symlink.js:55:25)
    at Object.<anonymous> (/tmp/.mount_ipfs-dxBTGy9/resources/app.asar/out/ipfs-on-path/scripts/install.js:62:21)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:850:10)
    at internal/main/run_main_module.js:17:11 {
  errno: -13,
  syscall: 'symlink',
  code: 'EACCES',
  path: '/tmp/.mount_ipfs-dxBTGy9/resources/app.asar.unpacked/out/ipfs-on-path/scripts/ipfs.sh',
  dest: '/usr/local/bin/ipfs'
}
```

**Comment by hacdias** [comment]
Despite the error, it seems to be okay and it should run normally. That error is because we automatically try to add `ipfs` to PATH if it's not there yet. If it errors, we just fail silently.

I don't know which distro you're using, but on most you'll see the IPFS Desktop icon on the tray/menu bar/task bar/app indicator.

**Comment by ibnesayeed** [comment]
> I don't know which distro you're using, but on most you'll see the IPFS Desktop icon on the tray/menu bar/task bar/app indicator.

In case of AppImages, an icon is added to the menu only after it's first launch after user approval for inclusion. However, I didn't see any window/dialogue opening in the first place. On a side note, I do not have IPFS installed or running, is it possible that the app is checking for that and halting without reporting anything?

My distro information is as following:

```
$ lsb_release -a
LSB Version:	core-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID:	elementary
Description:	elementary OS 5.0 Juno
Release:	5.0
Codename:	juno
```

On second run, the exception did not occur, but it did not launch anything either.

```
$ /tmp/ipfs-desktop-0.9.2-linux-x86_64.AppImage
2019-09-19T18:26:39.378Z info: [meta] logs can be found on /home/user/.config/IPFS Desktop
Checking for update
Update for version 0.9.2 is not available (latest version: 0.9.2, downgrade is disallowed).
2019-09-19T18:26:41.671Z info: [web ui] window ready
2019-09-19T18:26:41.672Z info: [tray] starting
2019-09-19T18:26:41.721Z info: [tray] started
2019-09-19T18:26:41.722Z info: [ipfsd] start daemon STARTED
2019-09-19T18:26:43.490Z info: [ipfsd] start daemon FINISHED 1.767780972957611s
2019-09-19T18:26:43.534Z info: [npm on ipfs] no action taken
2019-09-19T18:26:43.537Z info: [ipfs on path] no action taken
2019-09-19T18:26:43.538Z info: [launch on startup] disabled
[... HANGS HERE FOREVER ...]
```

>

**Comment by hacdias** [comment]
For the logs, it just seems it should work normally. Could you try a different package to make sure the problem is because of the packaging? Maybe .deb or even the .zip, please. Sorry for this

**Comment by ibnesayeed** [comment]
I tried `.AppImage`, `.tar.xz`, and `.deb` with no luck. They all are behaving the same way with the same error message in the first run and hang forever on subsequent runs.

**Comment by hacdias** [comment]
Just tried on Ubuntu and its working:

![image](https://user-images.githubusercontent.com/5447088/65409981-16b74380-dde1-11e9-96be-09e6054e804a.png)

It might be an incompatibility with Elementary's Desktop Environment. As far as I know, there are quite a few that removed the support for little app indicators such the one in the top bar in that screenshot.

**Comment by ibnesayeed** [comment]
So, this application utilizes system tray. That explains why it's not working on Elementary OS. [Elementary OS has deprecated status bar icons](https://github.com/elementary/wingpanel/issues/96) in the last version and completely removed in the current one. Even [GNOME does not like the idea of status icons](https://blogs.gnome.org/aday/2017/08/31/status-icons-and-gnome/).

While it is possible to [install and enable legacy behavior in Elementary OS](https://elementaryos.stackexchange.com/questions/17452/how-to-display-system-tray-icons-in-elementary-os-juno), I don't think I will go that far.

**Comment by hacdias** [comment]
Right now, this is a limitation of Electron. They haven't yet updated to the newest system and it doesn't seem they'll do so in the near future unfortunately: https://github.com/electron/electron/issues/10427

**Comment by ibnesayeed** [comment]
Could displaying the primary window on run be an option? If so, we perhaps should also make sure to kill any related background process first before reopening the window (because closing the window would perhaps keep the process running in the background and syncing).

**Comment by hacdias** [comment]
Close in favour of #1153.
