### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by pvinis** [ipfs-shipyard/ipfs-desktop#1138]
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: darwin
- **IPFS Desktop Version**: 0.8.0
- **Electron Version**: 5.0.2
- **Chrome Version**: 73.0.3683.121

**Error**

```
TypeError: Error processing argument at index 0, conversion failure from /Applications/IPFS Desktop.app/Contents/Resources/app.asar/assets/icons/tray/black.png
    at updateStatus (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/out/late/tray.js:182:12)
    at EventEmitter.<anonymous> (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/out/late/tray.js:193:5)
    at EventEmitter.emit (events.js:199:15)
    at updateStatus (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/out/late/register-daemon.js:55:33)
    at _callee3$ (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/out/late/register-daemon.js:189:25)
    at tryCatch (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at /Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at /Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12
    at stopIpfs (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/out/late/register-daemon.js:231:30)
    at _callee4$ (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/out/late/register-daemon.js:246:32)
    at tryCatch (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:45:40)
```

**Comment by hacdias** [comment]
Hello @pvinis! Thanks for the report. Would you mind updating to the [latest version](https://github.com/ipfs-shipyard/ipfs-desktop/releases) please?

**Comment by pvinis** [comment]
How do I do that? Do I need to uninstall and download fresh? I thought it would autoupdate. Can I check the current version I have?

**Comment by hacdias** [comment]
You have 0.8.0 as per the logs say. It should auto-update and I haven't had any issues in the previous versions. You need to accept the update after receiving a notification. It's semi-automatic. Can you try clicking on the menubar, About, Check for updates.

If you want to update manually, just download the DMG and install. No need to uninstall beforehand.

**Comment by pvinis** [comment]
Ah, alright, I seem to have 0.9.2 now, which is the latest.

**Comment by hacdias** [comment]
Please let me know if you get any crash in the future. However, looking at your logs, I can't actually seem to find why's this happened.

**Comment by pvinis** [comment]
No problem. I will close this, and if something similar happens, I'll report back. Thank you :)
