### ISSUE TITLE
Crashing when selecting "add command-line tools to PATH"

### ISSUE THREAD

**Issue by drowse7en** [ipfs-shipyard/ipfs-desktop#1167]
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.9.1
- **Electron Version**: 6.0.7
- **Chrome Version**: 76.0.3809.139

**Error**

```
TypeError: Cannot read property 'trySudo' of undefined
    at _callee5$ (C:\Users\desic\AppData\Local\Programs\ipfs-desktop\resources\app.asar\out\ipfs-on-path\index.js:212:35)
    at tryCatch (C:\Users\desic\AppData\Local\Programs\ipfs-desktop\resources\app.asar\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (C:\Users\desic\AppData\Local\Programs\ipfs-desktop\resources\app.asar\node_modules\regenerator-runtime\runtime.js:271:22)
    at Generator.prototype.<computed> [as next] (C:\Users\desic\AppData\Local\Programs\ipfs-desktop\resources\app.asar\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (C:\Users\desic\AppData\Local\Programs\ipfs-desktop\resources\app.asar\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\desic\AppData\Local\Programs\ipfs-desktop\resources\app.asar\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\desic\AppData\Local\Programs\ipfs-desktop\resources\app.asar\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\desic\AppData\Local\Programs\ipfs-desktop\resources\app.asar\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at _run (C:\Users\desic\AppData\Local\Programs\ipfs-desktop\resources\app.asar\out\ipfs-on-path\index.js:238:15)
```

**Comment by hacdias** [comment]
Hello @drowse7en! Thanks for the report. That was fixed on 0.9.2 already. Please upgrade by [downloading the latest version](https://github.com/ipfs-shipyard/ipfs-desktop/releases) or click on IPFS Desktop -> About -> Check for Updates... . Please let me know if there is any issue upgrading!
