### ISSUE TITLE
Crash. Ctrl-Z

### ISSUE THREAD

**Issue by tonuonu** [ipfs-shipyard/ipfs-desktop#1255]
I think this problem is related to fact that I opened terminal, ran "ipfs-desktop" then pressed Ctrl-Z, then told command "bg" and "exit".
**Specifications**

- **OS**: linux
- **IPFS Desktop Version**: 0.10.0
- **Electron Version**: 7.1.1
- **Chrome Version**: 78.0.3904.99

**Error**

```
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:414:19)
    at writeOrBuffer (_stream_writable.js:402:5)
    at WriteStream.Writable.write (_stream_writable.js:302:11)
    at Console.log (/opt/IPFS Desktop/resources/app.asar/node_modules/winston/lib/winston/transports/console.js:79:23)
    at Console._write (/opt/IPFS Desktop/resources/app.asar/node_modules/winston-transport/index.js:81:19)
    at doWrite (/opt/IPFS Desktop/resources/app.asar/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/opt/IPFS Desktop/resources/app.asar/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Console.Writable.write (/opt/IPFS Desktop/resources/app.asar/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at DerivedLogger.ondata (/opt/IPFS Desktop/resources/app.asar/node_modules/winston/node_modules/readable-stream/lib/_stream_readable.js:662:20)
    at DerivedLogger.emit (events.js:208:15)
```

**Comment by hacdias** [comment]
Interesting. I CTRL-Z a lot of times and never got an error like this one. Might be because it's Linux. I'll check if Electron handles the signals or not.

**Comment by hacdias** [comment]
Has this ever happened to you again?

**Comment by jessicaschilling** [comment]
Closing due to inactivity, but please open a thread on discuss.ipfs.io if further troubleshooting is needed. Thank you!
