### ISSUE TITLE
Downloaded app image crashes on start 'symlink' access error

### ISSUE THREAD

**Issue by edwin-oetelaar** [ipfs-shipyard/ipfs-desktop#1301]
downloaded image here : 
https://github.com/ipfs-shipyard/ipfs-desktop/releases/download/v0.10.2/ipfs-desktop-0.10.2-linux-x86_64.AppImage

Check what kind of file it is :

file ipfs-desktop-0.10.2-linux-x86_64.AppImage 

ipfs-desktop-0.10.2-linux-x86_64.AppImage: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/l, for GNU/Linux 2.6.18, stripped

Make executable :

oetelaar@DT-Helmond:~/Downloads$ chmod +x ipfs-desktop-0.10.2-linux-x86_64.AppImage 

Run it :

oetelaar@DT-Helmond:~/Downloads$ ./ipfs-desktop-0.10.2-linux-x86_64.AppImage 

Warnings from gtk :

(ipfs-desktop:19190): Gtk-WARNING **: 13:11:36.420: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(ipfs-desktop:19190): Gtk-WARNING **: 13:11:36.420: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(ipfs-desktop:19190): Gtk-WARNING **: 13:11:36.420: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
2019-12-21T12:11:37.048Z info: [meta] logs can be found on /home/oetelaar/.config/IPFS Desktop
(node:19190) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
(node:19190) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
Checking for update
Generated new staging user ID: 57c3c941-1822-578f-ab74-c60c33cef565
Update for version 0.10.2 is not available (latest version: 0.10.2, downgrade is disallowed).
2019-12-21T12:11:39.359Z info: [web ui] window ready
2019-12-21T12:11:39.359Z info: [tray] starting
2019-12-21T12:11:39.387Z info: [tray] started
2019-12-21T12:11:39.387Z info: [ipfsd] start daemon STARTED
2019-12-21T12:11:40.495Z info: [daemon] gateway port busy
Gtk-Message: 13:11:40.549: GtkDialog mapped without a transient parent. This is discouraged.
2019-12-21T12:12:09.297Z info: [daemon] ports updated
2019-12-21T12:12:10.065Z info: [ipfsd] start daemon FINISHED 30.677251384735108s
2019-12-21T12:12:10.105Z info: [npm on ipfs] 1st time running and package is not installed
2019-12-21T12:12:10.112Z info: [npm on ipfs] no action taken
2019-12-21T12:12:10.121Z info: [launch on startup] disabled
2019-12-21T12:12:10.207Z info: [ipfs on path] no-sudo: stderr: fs.js:126
    throw err;
    ^

**It stops working**

Error: EACCES: permission denied, symlink '/tmp/.mount_ipfs-dIn8Cte/resources/app.asar.unpacked/out/ipfs-on-path/scripts/ipfs.sh' -> '/usr/local/bin/ipfs'
    at Object.symlinkSync (fs.js:935:3)
    at Object.createSymlinkSync (/tmp/.mount_ipfs-dIn8Cte/resources/app.asar/node_modules/fs-extra/lib/ensure/symlink.js:55:25)
    at Object.<anonymous> (/tmp/.mount_ipfs-dIn8Cte/resources/app.asar/out/ipfs-on-path/scripts/install.js:62:21)
    at Module._compile (internal/modules/cjs/loader.js:880:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
    at Module.load (internal/modules/cjs/loader.js:735:32)
    at Module._load (internal/modules/cjs/loader.js:648:12)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Function.Module.runMain (internal/modules/cjs/loader.js:944:10) {
  **errno: -13,
  syscall: 'symlink',
  code: 'EACCES',
  path: '/tmp/.mount_ipfs-dIn8Cte/resources/app.asar.unpacked/out/ipfs-on-path/scripts/ipfs.sh',
  dest: '/usr/local/bin/ipfs'
}**

^C

This is a normal linux system, i9 based

at /proc/cpuinfo 
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 158
model name	: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
stepping	: 12
microcode	: 0xae
cpu MHz		: 800.033
cache size	: 16384 KB
physical id	: 0

Running Ubuntu :+1: Linux DT-Helmond 4.18.0-15-generic #16~18.04.1-Ubuntu SMP Thu Feb 7 14:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Nothing special as far as I can see.

I will try DEB package now...

**Comment by alphanmoon** [comment]
The same issue using Debian 10. Appimage doesn't roll.

**Comment by lidel** [comment]
@alphanmoon is this still a problem with [v0.13.2](https://github.com/ipfs-shipyard/ipfs-desktop/releases/tag/v0.13.2)?

**Comment by lidel** [comment]
I am afraid the only fix here is to find `IPFS Desktop/config.json` and manually set:
```json
"ipfsOnPath": false,
```
We will be deprecating this feature (https://github.com/ipfs-shipyard/ipfs-desktop/pull/1768), if you want `ipfs` on your `PATH`   follow https://docs.ipfs.io/install/command-line/
