### ISSUE TITLE
not go

### ISSUE THREAD

**Issue by yhf213** [ipfs-shipyard/ipfs-desktop#1348]
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.10.3
- **Electron Version**: 7.1.11
- **Chrome Version**: 78.0.3904.130

**Error**

```
Error: spawn powershell.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

**Comment by jessicaschilling** [comment]
Closing due to inactivity; however, please feel free to open a thread on discuss.ipfs.io if further troubleshooting is needed. Thank you!
