### ISSUE TITLE
IPFS installation error on windows

### ISSUE THREAD

**Issue by DivyaGayatriKota** [ipfs-shipyard/ipfs-desktop#1357]
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.10.3
- **Electron Version**: 7.1.11
- **Chrome Version**: 78.0.3904.130

**Error**

```
Error: spawn EPERM
    at ChildProcess.spawn (internal/child_process.js:394:11)
    at spawn (child_process.js:553:9)
    at execFile (child_process.js:237:17)
    at module.<computed> (electron/js2c/asar.js:163:31)
    at C:\Users\di20090672\AppData\Local\Programs\IPFS Desktop\resources\app.asar\out\ipfs-on-path\index.js:171:43
    at new Promise (<anonymous>)
    at _callee4$ (C:\Users\di20090672\AppData\Local\Programs\IPFS Desktop\resources\app.asar\out\ipfs-on-path\index.js:170:47)
    at tryCatch (C:\Users\di20090672\AppData\Local\Programs\IPFS Desktop\resources\app.asar\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (C:\Users\di20090672\AppData\Local\Programs\IPFS Desktop\resources\app.asar\node_modules\regenerator-runtime\runtime.js:271:22)
    at Generator.prototype.<computed> [as next] (C:\Users\di20090672\AppData\Local\Programs\IPFS Desktop\resources\app.asar\node_modules\regenerator-runtime\runtime.js:97:21)
```

**Comment by lidel** [comment]
@DivyaGayatriKota can you retry with [v0.10.4](https://github.com/ipfs-shipyard/ipfs-desktop/releases/tag/v0.10.4), please?

**Comment by hacdias** [comment]
Closing this due to inactivity.
