### ISSUE TITLE
stopIpfs is not a function

### ISSUE THREAD

**Issue by dimka511** [ipfs-shipyard/ipfs-desktop#1375]
I clicked update IPFS and an error window appeared.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.10.3
- **Electron Version**: 7.1.11
- **Chrome Version**: 78.0.3904.130

**Error**

```
TypeError: stopIpfs is not a function
    at _callee$ (D:\network\IPFS\resources\app.asar\out\auto-updater\quit-and-install.js:42:20)
    at tryCatch (D:\network\IPFS\resources\app.asar\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (D:\network\IPFS\resources\app.asar\node_modules\regenerator-runtime\runtime.js:271:22)
    at Generator.prototype.<computed> [as next] (D:\network\IPFS\resources\app.asar\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (D:\network\IPFS\resources\app.asar\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\network\IPFS\resources\app.asar\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\network\IPFS\resources\app.asar\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at D:\network\IPFS\resources\app.asar\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at _quitAndInstall (D:\network\IPFS\resources\app.asar\out\auto-updater\quit-and-install.js:58:26)
```

**Comment by hacdias** [comment]
Does this happen with 0.10.4?
