### ISSUE TITLE
update button doesn't work

### ISSUE THREAD

**Issue by sixcorners** [ipfs-shipyard/ipfs-desktop#1446]
Please describe what you were doing when this error happened.
I clicked the notification that offered to update my ipfs installation.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.10.3
- **Electron Version**: 7.1.11
- **Chrome Version**: 78.0.3904.130

**Error**

```
TypeError: stopIpfs is not a function
    at _callee$ (C:\Program Files\IPFS Desktop\resources\app.asar\out\auto-updater\quit-and-install.js:42:20)
    at tryCatch (C:\Program Files\IPFS Desktop\resources\app.asar\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (C:\Program Files\IPFS Desktop\resources\app.asar\node_modules\regenerator-runtime\runtime.js:271:22)
    at Generator.prototype.<computed> [as next] (C:\Program Files\IPFS Desktop\resources\app.asar\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (C:\Program Files\IPFS Desktop\resources\app.asar\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Program Files\IPFS Desktop\resources\app.asar\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Program Files\IPFS Desktop\resources\app.asar\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Program Files\IPFS Desktop\resources\app.asar\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at _quitAndInstall (C:\Program Files\IPFS Desktop\resources\app.asar\out\auto-updater\quit-and-install.js:58:26)
```

**Comment by sixcorners** [comment]
Duplicate of #1375
