### ISSUE TITLE
Crash. Just bad internet .

### ISSUE THREAD

**Issue by tonuonu** [ipfs-shipyard/ipfs-desktop#1482]
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: darwin
- **IPFS Desktop Version**: 0.11.2
- **Electron Version**: 8.2.4
- **Chrome Version**: 80.0.3987.165

**Error**

```
TypeError: Cannot read property 'pid' of null
    at Timeout._onTimeout (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/ipfsd-ctl/src/ipfsd-daemon.js:243:101)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

**Comment by lidel** [comment]
We switched to the latest ipfsd-ctl in  [v0.13.2](https://github.com/ipfs-shipyard/ipfs-desktop/releases/tag/v0.13.2) – please upgrade.
