### ISSUE TITLE
npm-on-ipfs experiment unable to update config

### ISSUE THREAD

**Issue by HulaCloud** [ipfs-shipyard/ipfs-desktop#1515]
I was out of the room and the PC was idle so I don't why it crashed.

**Specifications**

- **OS**: linux
- **IPFS Desktop Version**: 0.11.2
- **Electron Version**: 8.2.4
- **Chrome Version**: 80.0.3987.165

**Error**

```
Error: EACCES: permission denied, open '/home/terence/snap/ipfs-desktop/17/.config/IPFS Desktop/config.json'
    at Object.openSync (fs.js:440:3)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as openSync] (electron/js2c/asar.js:140:31)
    at Object.writeFileSync (fs.js:1265:35)
    at ElectronStore._write (/snap/ipfs-desktop/17/resources/app.asar/node_modules/conf/index.js:177:7)
    at ElectronStore.set store [as store] (/snap/ipfs-desktop/17/resources/app.asar/node_modules/conf/index.js:461:8)
    at ElectronStore.set (/snap/ipfs-desktop/17/resources/app.asar/node_modules/conf/index.js:339:14)
    at Timeout.existsAndUpdate [as _onTimeout] (/snap/ipfs-desktop/17/resources/app.asar/src/npm-on-ipfs/index.js:38:11)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

**Comment by lidel** [comment]
@HulaCloud please upgrade to the latest Snap (`v0.13.0`) and reopen if the issue still occurs.
