### ISSUE TITLE
Unable to start or connect to the IPFS daemon

### ISSUE THREAD

**Issue by jayschwa** [ipfs-shipyard/ipfs-desktop#1525]
- OS: Ubuntu 20.04 / Linux
 - IPFS Desktop v0.11.4

**Describe the bug**

IPFS Desktop is unable to start or connect to the IPFS daemon. I believe the IPFS daemon is failing to start because I only see `ipfs-desktop` processes when I `pgrep -l ipfs`.

**To Reproduce**

1. Open IPFS Desktop.

**Expected behavior**

The IPFS daemon starts and the web UI connects to it.

**Additional context**

This was not the case a week or two ago, so I suspect the problem started with an upgrade.

I am using the `snap` package manager.

~Sorry for lack of logs, but I see no obvious `Advanced` → `Open Logs Directory` button or menu in the UI. If this menu is under the tray icon, I cannot see it because I am also affected by #1522.~

Update: I have found the error logs. `snap` keeps them nestled away at `~/snap/ipfs-desktop/current/.config/IPFS Desktop`, not my usual `~/.config`.

```
2020-05-27T03:54:20.899Z error: [ipfsd] start daemon SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Daemon._getConfig (/snap/ipfs-desktop/19/resources/app.asar/node_modules/ipfsd-ctl/src/ipfsd-daemon.js:303:19)
    at async Daemon.init (/snap/ipfs-desktop/19/resources/app.asar/node_modules/ipfsd-ctl/src/ipfsd-daemon.js:129:9)
    at async spawn (/snap/ipfs-desktop/19/resources/app.asar/src/daemon/daemon.js:65:3)
    at async module.exports (/snap/ipfs-desktop/19/resources/app.asar/src/daemon/daemon.js:74:31)
    at async startIpfs (/snap/ipfs-desktop/19/resources/app.asar/src/daemon/index.js:54:15)
    at async module.exports (/snap/ipfs-desktop/19/resources/app.asar/src/daemon/index.js:120:3)
    at async run (/snap/ipfs-desktop/19/resources/app.asar/src/index.js:71:5)
2020-05-27T03:54:20.912Z error: [updater] Error: ENOENT: no such file or directory, open '/snap/ipfs-desktop/19/resources/app-update.yml'
```

**Comment by jayschwa** [comment]
I experience this issue only when using the snap package. The daemon starts when using the Debian package.

**Comment by jessicaschilling** [comment]
@lidel @rafaelramalho19 or @olizilla -- might you be able to triage? Thank you!

**Comment by lidel** [comment]
@jayschwa does the issue still occurs with [`ipfs-desktop-0.12.2-linux-amd64.snap`](https://github.com/ipfs-shipyard/ipfs-desktop/releases/download/v0.12.2/ipfs-desktop-0.12.2-linux-amd64.snap)?

**Comment by jayschwa** [comment]
No, it appears to work with the 0.12.2 snap. I will close this issue. Do you plan to publish new builds to the Snap Store?

**Comment by lidel** [comment]
@jayschwa for snap publishing, see https://github.com/ipfs-shipyard/ipfs-desktop/issues/1551#issuecomment-658828753
