### ISSUE TITLE
eror npm via ipfs

### ISSUE THREAD

**Issue by diego83200** [ipfs-shipyard/ipfs-desktop#1529]
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.11.4
- **Electron Version**: 8.2.5
- **Chrome Version**: 80.0.3987.165

**Error**

```
Error: spawn npm.cmd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by lidel** [comment]
Continued in https://github.com/ipfs-shipyard/ipfs-desktop/issues/1504
