### ISSUE TITLE
Crash on open

### ISSUE THREAD

**Issue by ilmtr** [ipfs-shipyard/ipfs-desktop#1554]
IPFS Desktop keeps crashing when i try to open it. I have tried uninstalling and reinstalling it, but the issue returns.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.11.4
- **Electron Version**: 8.2.5
- **Chrome Version**: 80.0.3987.165

**Error**

```
Error: EPERM: operation not permitted, open 'C:\Users\User\.ipfs-desktop\IPFS_PATH'
    at Object.openSync (fs.js:440:3)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as openSync] (electron/js2c/asar.js:140:31)
    at Object.writeFileSync (fs.js:1265:35)
    at Object.outputFileSync (C:\Users\User\AppData\Local\Programs\IPFS Desktop\resources\app.asar\node_modules\fs-extra\lib\output\index.js:31:15)
    at writeIpfsPath (C:\Users\User\AppData\Local\Programs\IPFS Desktop\resources\app.asar\src\daemon\index.js:134:6)
    at startIpfs (C:\Users\User\AppData\Local\Programs\IPFS Desktop\resources\app.asar\src\daemon\index.js:50:7)
    at module.exports (C:\Users\User\AppData\Local\Programs\IPFS Desktop\resources\app.asar\src\daemon\index.js:120:9)
    at run (C:\Users\User\AppData\Local\Programs\IPFS Desktop\resources\app.asar\src\index.js:71:11)
```

**Comment by rafaelramalho19** [comment]
Have you tried deleting both `C:\Users\User\AppData\Local\Programs\IPFS Desktop\` and `'C:\Users\User\.ipfs-desktop\` and reinstalling?

**Comment by ilmtr** [comment]
I have deleted these folders, and in addition also the _"C:\Users\User\AppData\Roaming\IPFS Dekstop"_ folder. Then uninstalled and reinstalled IPFS Desktop, and also selected install for all users, instead of just me.  

IPFS Desktop now opens and runs without crashing now, thank you!
