### ISSUE TITLE
IPFS having trouble updating

### ISSUE THREAD

**Issue by JamesCarnley** [ipfs-shipyard/ipfs-desktop#1585]
Please describe what you were doing when this error happened.

IPFS modal asking for a restart to update popped up. Click restart. IPFS never started up again. Launching IPFS again triggers same popup and IPFS quits. Launching IPFS and selecting Check for updates produces this error.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.12.1
- **Electron Version**: 8.2.5
- **Chrome Version**: 80.0.3987.165

**Error**

```
TypeError: ctx.checkForUpdates is not a function
    at click (C:\Users\James\AppData\Local\Programs\ipfs-desktop\resources\app.asar\src\tray.js:198:30)
    at MenuItem.click (electron/js2c/browser_init.js:1501:9)
    at Function.executeCommand (electron/js2c/browser_init.js:1762:13)
```

**Comment by JamesCarnley** [comment]
Additionally clicking restart on the modal popup triggered this error

```
TypeError: Object has been destroyed
    at updateMenu (C:\Users\James\AppData\Local\Programs\ipfs-desktop\resources\app.asar\src\tray.js:306:12)
    at IpcMainImpl.<anonymous> (C:\Users\James\AppData\Local\Programs\ipfs-desktop\resources\app.asar\src\tray.js:323:5)
    at IpcMainImpl.emit (events.js:215:7)
    at updateStatus (C:\Users\James\AppData\Local\Programs\ipfs-desktop\resources\app.asar\src\daemon\index.js:17:13)
    at stopIpfs (C:\Users\James\AppData\Local\Programs\ipfs-desktop\resources\app.asar\src\daemon\index.js:94:7)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by jessicaschilling** [comment]
@rafaelramalho19, do you mind having a look when you're back "at the office"? Thanks!

**Comment by InSimpleTermsJordan** [comment]
Same with Windows 10 Home, 64-bit. Same issue occurred with 0.12.0 as well when 0.12.1 came out, IIRC.

**Comment by rafaelramalho19** [comment]
Thank you for creating the issue @JamesCarnley. 

I couldn't replicate this with a normal installation of 0.12.1 and updating. Also clicked "check for updates" and worked without any issues 🤔 

If you don't mind doing a "reboot" on ipfs-desktop (you can lose data by doing this, so watch out 😄), can you please delete `C:\Users\User\AppData\Local\Programs\IPFS Desktop\`, `C:\Users\User\AppData\Roaming\IPFS Dekstop` and `C:\Users\User\.ipfs-desktop\` and reinstall the app?

**Comment by JamesCarnley** [comment]
Deleting the folders and reinstalling did fix it. Sorry I couldn't provide more details.

**Comment by dickvangelder** [comment]
I read the above suggestion from @rafaelramalho19 to 'reboot'.

C:\Users\User\AppData\Local\Programs\IPFS Desktop\ : There is no IPFS Desktop folder the Programs folder.
C:\Users\User\AppData\Roaming\IPFS Dekstop  : I renamed this folder.
C:\Users\User\.ipfs-desktop\ : I renamed this folder.

There is also a C:\Users\User\.ipfs folder : I did not rename or delete this one.

I uninstalled version 0.12.2 and reinstalled it.

Still errors.

[error.log](https://github.com/ipfs-shipyard/ipfs-desktop/files/4995281/error.log)
