### ISSUE TITLE
TypeError while tray.setImage to off-big.png

### ISSUE THREAD

**Issue by ghost** [ipfs-shipyard/ipfs-desktop#1602]
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: linux
- **IPFS Desktop Version**: 0.11.4
- **Electron Version**: 8.2.5
- **Chrome Version**: 80.0.3987.165

**Error**

```
TypeError: Error processing argument at index 0, conversion failure from /opt/IPFS Desktop/resources/app.asar/assets/icons/tray/off-big.png
    at updateMenu (/opt/IPFS Desktop/resources/app.asar/src/tray.js:306:12)
    at IpcMainImpl.<anonymous> (/opt/IPFS Desktop/resources/app.asar/src/tray.js:323:5)
    at IpcMainImpl.emit (events.js:215:7)
    at updateStatus (/opt/IPFS Desktop/resources/app.asar/src/daemon/index.js:17:13)
    at stopIpfs (/opt/IPFS Desktop/resources/app.asar/src/daemon/index.js:79:5)
    at restartIpfs (/opt/IPFS Desktop/resources/app.asar/src/daemon/index.js:101:11)
    at IpcMainImpl.<anonymous> (/opt/IPFS Desktop/resources/app.asar/src/daemon/index.js:124:7)
    at IpcMainImpl.emit (events.js:210:5)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3851:15)
    at WebContents.emit (events.js:210:5)
```

**Comment by jessicaschilling** [comment]
@rafaelramalho19 and/or @lidel, could you please triage? Thank you!

**Comment by lidel** [comment]
https://github.com/ipfs-shipyard/ipfs-desktop/blob/v0.11.4/src/tray.js#L306 could be related to https://github.com/ipfs-shipyard/ipfs-desktop/issues/1153

@WildeGeist please update to [v0.12.2](https://github.com/ipfs-shipyard/ipfs-desktop/releases/tag/v0.12.2) and let us know if that helped. 
If not, let us know what is your Linux distro and Desktop Environment.

**Comment by lidel** [comment]
Unable to replicate, but assuming switch to Electron 9 in v0.13 fixes this bug. 
Feel free to reopen if the issue is still occuring after the update.
