### ISSUE TITLE
ipfs installtion error

### ISSUE THREAD

**Issue by rajaroy43** [ipfs-shipyard/ipfs-desktop#1604]
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.11.4
- **Electron Version**: 8.2.5
- **Chrome Version**: 80.0.3987.165

**Error**

```
Error: EBUSY: resource busy or locked, rename 'C:\Users\raja roy\AppData\Roaming\IPFS Desktop\config.json.978347352' -> 'C:\Users\raja roy\AppData\Roaming\IPFS Desktop\config.json'
    at Object.renameSync (fs.js:643:3)
    at Function.writeFileSync [as sync] (C:\Program Files\IPFS Desktop\resources\app.asar\node_modules\write-file-atomic\index.js:244:8)
    at ElectronStore._write (C:\Program Files\IPFS Desktop\resources\app.asar\node_modules\conf\index.js:180:21)
    at ElectronStore.set store [as store] (C:\Program Files\IPFS Desktop\resources\app.asar\node_modules\conf\index.js:461:8)
    at ElectronStore.set (C:\Program Files\IPFS Desktop\resources\app.asar\node_modules\conf\index.js:339:14)
    at C:\Program Files\IPFS Desktop\resources\app.asar\src\webui\index.js:88:11
    at IpcMainImpl.<anonymous> (C:\Program Files\IPFS Desktop\resources\app.asar\src\utils\create-toggler.js:10:15)
    at IpcMainImpl.emit (events.js:210:5)
    at click (C:\Program Files\IPFS Desktop\resources\app.asar\src\tray.js:33:28)
    at MenuItem.click (electron/js2c/browser_init.js:1501:9)
```

**Comment by rafaelramalho19** [comment]
Can you please describe what were you doing during the error occurrence?

**Comment by lidel** [comment]
@rajaroy43 a lot changed since 0.11.4, including electron update to 9.x. 
Please update ipfs-desktop  to [v0.13.2](https://github.com/ipfs-shipyard/ipfs-desktop/releases/tag/v0.13.2). If you experience this issue again, feel free to reopen.

**Comment by rajaroy43** [comment]
A lot of bugs in the windows ipfs desktop i think you must fix these buges.
Let take an example if i upload some Image on Ipfs and share that link with
you then it some time work and sometime not it's not what we expect from
ipfs

**Comment by jessicaschilling** [comment]
@rajaroy43 Please download and try out [v0.13.2](https://github.com/ipfs-shipyard/ipfs-desktop/releases/tag/v0.13.2) - many things have been tweaked and improved. Thank you!

**Comment by rajaroy43** [comment]
new version is 0.13 ...i see on github
