### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ksnyde** [ipfs-shipyard/ipfs-desktop#1607]
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: darwin
- **IPFS Desktop Version**: 0.12.2
- **Electron Version**: 8.2.5
- **Chrome Version**: 80.0.3987.165

**Error**

```
Error: Command failed: npm install -g ipfs-npm
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EHOSTDOWN: request to https://registry.npmjs.org/ipfs-npm failed, reason: connect EHOSTDOWN 104.16.21.35:443 - Local (0.0.0.0:0)
npm WARN registry Using stale data from https://registry.npmjs.org/ due to a request error during revalidation.
npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated boom@7.3.0: This module has moved and is now available at @hapi/boom. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated multicodec@0.5.7: stable api reached
npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated libp2p-connection-manager@0.1.0: libp2p-connection-manager is now part of libp2p as of libp2p@0.26.1. This module should no longer be used standalone.
npm WARN deprecated libp2p-ping@0.8.5: libp2p-ping is now part of libp2p as of libp2p@0.26.1. This module should no longer be used standalone.
npm WARN deprecated libp2p-switch@0.42.12: libp2p-switch is now part of libp2p as of libp2p@0.26.1. This module should no longer be used standalone.
npm WARN deprecated libp2p-circuit@0.3.7: Circuit is now part of libp2p as of libp2p@0.26.1. This module should no longer be used standalone.
npm WARN deprecated libp2p-identify@0.7.6: libp2p-identify is now part of libp2p as of libp2p@0.26.1. This module should no longer be used standalone.
npm ERR! code EHOSTDOWN
npm ERR! errno EHOSTDOWN
npm ERR! request to https://registry.npmjs.org/aws-sdk/-/aws-sdk-2.728.0.tgz failed, reason: connect EHOSTDOWN 104.16.21.35:443 - Local (0.0.0.0:0)

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ken/.npm/_logs/2020-08-12T08_10_51_933Z-debug.log

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

**Comment by jessicaschilling** [comment]
@lidel or @rafaelramalho19, can you please have a look when you get the chance?

**Comment by lidel** [comment]
@ksnyde I assume this happens when you enabled NPM integration? 
It installs additional packages, meaning this was either a network error on your end, or https://registry.npmjs.org being down. 

Trying again after an hour or so should fix the issue. 

Feel free to reopen if the issue is still present, and let us know if you are able to download https://registry.npmjs.org/aws-sdk/-/aws-sdk-2.728.0.tgz with your browser.

**Comment by ksnyde** [comment]
@lidel I setup the integration a long while back (maybe a year ago or so). Sadly I don't remember with high resolution what triggered this message to come up except to say that I didn't actually type the npm command being stated here (aka, `npm install -g ipfs-npm`). I mean I did a year or so ago when I first installed it of course but not when reporting this error. Is it possible that the process of my desktop IPFS client being updated that it attempted to update this too?

**Comment by lidel** [comment]
Kinda: if you opted-in to the  "npm on ipfs" experiment, then `npm install -g ipfs-npm` is executed every 12 hours by ipfs-desktop behind the scenes:  https://github.com/ipfs-shipyard/ipfs-desktop/blob/v0.12.2/src/npm-on-ipfs/index.js#L12-L14
