### ISSUE TITLE
Upgrade error

### ISSUE THREAD

**Issue by bloxster** [ipfs-shipyard/ipfs-desktop#1612]
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: darwin
- **IPFS Desktop Version**: 0.12.2
- **Electron Version**: 8.2.5
- **Chrome Version**: 80.0.3987.165

**Error**

```
Error: Command failed: npm install -g ipfs-npm
npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated boom@7.3.0: This module has moved and is now available at @hapi/boom. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated multicodec@0.5.7: stable api reached
npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/hugomrdias/concat-stream.git
npm ERR! 
npm ERR! xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm ERR! 
npm ERR! exited with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/gmr/.npm/_logs/2020-08-20T21_14_58_652Z-debug.log

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

**Comment by jessicaschilling** [comment]
Thanks, @bloxster! We'll bring this up in our next weekly triage meeting.

**Comment by jessicaschilling** [comment]
Hi @bloxster -- can you please try disabling the 'npm on IPFS' experiment under the cube menu? This should take care of the issue in the immediacy. We're aware of the underlying issue, so I'll close this, but please let us know if you continue to have issues.

![image](https://user-images.githubusercontent.com/1507828/91196245-2311e380-e6b7-11ea-9238-52c7c64d4441.png)
