### ISSUE TITLE
Advanced → "Open [..] directory" cause fatal crash

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs-shipyard/ipfs-desktop#1676]
I'm repeatedly killing Desktop when trying to select the following options under `Advanced`:
- `Open Logs Directory`
- `Open Repository Directory`
- `Open Configuration File`

**Specifications**

- **OS**: darwin
- **IPFS Desktop Version**: 0.13.0
- **Electron Version**: 9.3.2
- **Chrome Version**: 83.0.4103.122

**Error**

```
TypeError: shell.openItem is not a function
    at click (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/src/tray.js:141:32)
    at MenuItem.click (electron/js2c/browser_init.js:65:1624)
    at Function.executeCommand (electron/js2c/browser_init.js:73:1102)
```

**Comment by lidel** [comment]
I can confirm the same error on Linux.


**Specifications**

- **OS**: linux
- **IPFS Desktop Version**: 0.13.0
- **Electron Version**: 9.3.2
- **Chrome Version**: 83.0.4103.122

**Error**

```
TypeError: shell.openItem is not a function
    at click (/home/lidel/tmp/test-13/ipfs-desktop-0.13.0-rc3/ipfs-desktop-0.13.0-linux-x64/resources/app.asar/src/tray.js:141:32)
    at MenuItem.click (electron/js2c/browser_init.js:65:1624)
    at Function.executeCommand (electron/js2c/browser_init.js:73:1102)
```

**Comment by lidel** [comment]
Potential duplicate: https://github.com/ipfs-shipyard/ipfs-desktop/issues/1677
