### ISSUE TITLE
electron-updater errors on Linux

### ISSUE THREAD

**Issue by NukeManDan** [ipfs-shipyard/ipfs-desktop#1683]
- OS: Linux
 - Version of IPFS Desktop v0.13.0

**Describe the bug**
I get a non-fatal error when trying to update as described below. 

Ported from [this web-ui issue](https://github.com/ipfs-shipyard/ipfs-webui/issues/1665)

**To Reproduce**
1. right click tray icon 
2. About...
3. Check for updates....
4. Error (see attached files)

**Expected behavior**
Updating the GUI and CLI :pray:

**Additional context**
Also can confirm #1676 - I can't open logs dir from the tray icon. Crashes the app.

<details>
  <summary>terminal output on startup, try update via stem tray icon</summary>

```
2020-10-08T23:27:41.997Z info: [meta] logs can be found on /home/dan/.config/IPFS Desktop
Error: ENOTDIR: not a directory, mkdir '/opt/IPFS Desktop/resources/app.asar/node_modules/countly-sdk-nodejs/data'
    at Object.mkdirSync (fs.js:823:3)
    at Object.Countly.init (/opt/IPFS Desktop/resources/app.asar/node_modules/countly-sdk-nodejs/lib/countly.js:157:24)
    at module.exports (/opt/IPFS Desktop/resources/app.asar/src/analytics.js:6:11)
    at run (/opt/IPFS Desktop/resources/app.asar/src/index.js:65:11)
Error: ENOENT, node_modules/countly-sdk-nodejs/data/__cly_id.json not found in /opt/IPFS Desktop/resources/app.asar
    at createError (electron/js2c/asar.js:111:17)
    at Object.func [as openSync] (electron/js2c/asar.js:146:27)
    at Object.writeFileSync (fs.js:1265:35)
    at storeSet (/opt/IPFS Desktop/resources/app.asar/node_modules/countly-sdk-nodejs/lib/countly.js:1337:16)
    at Object.Countly.init (/opt/IPFS Desktop/resources/app.asar/node_modules/countly-sdk-nodejs/lib/countly.js:171:21)
    at module.exports (/opt/IPFS Desktop/resources/app.asar/src/analytics.js:6:11)
    at run (/opt/IPFS Desktop/resources/app.asar/src/index.js:65:11)
2020-10-08T23:27:42.800Z info: [web ui] window ready
2020-10-08T23:27:42.801Z info: [web ui] navigate to /
2020-10-08T23:27:42.855Z info: [tray] starting
2020-10-08T23:27:42.893Z info: [tray] started
2020-10-08T23:27:42.894Z info: [ipfsd] start daemon STARTED
2020-10-08T23:27:45.185Z info: [daemon] PeerID is Qmb61NjeYWBAUHHfXdZQp2MED8XuXRWrRgrFDG4xtBTQvA
2020-10-08T23:27:45.185Z info: [daemon] Repo is at /home/dan/.ipfs
2020-10-08T23:27:45.186Z info: [ipfsd] start daemon FINISHED 2.2916648849993946s
Checking for update
Error: Error: ENOENT: no such file or directory, open '/opt/IPFS Desktop/resources/app-update.yml'
2020-10-08T23:27:45.240Z error: [updater] Error: ENOENT: no such file or directory, open '/opt/IPFS Desktop/resources/app-update.yml'
2020-10-08T23:27:45.244Z info: [ipfs on path] no action taken
2020-10-08T23:27:45.246Z info: [launch on startup] disabled
Checking for update
Error: Error: ENOENT: no such file or directory, open '/opt/IPFS Desktop/resources/app-update.yml'
2020-10-08T23:29:28.330Z error: [updater] Error: ENOENT: no such file or directory, open '/opt/IPFS Desktop/resources/app-update.yml'
```

</details>

[error.log](https://github.com/ipfs-shipyard/ipfs-desktop/files/5351739/error.log)
[combined.log](https://github.com/ipfs-shipyard/ipfs-desktop/files/5351740/combined.log)

**Comment by lidel** [comment]
@NukeManDan what package type are you using?

On Linux only `AppImage` uses `app-update.yml`, everything else assumes third-party package manager is used.
Unless this is a bug in `AppImage`, the bug here is that we should disable auto update mechanism in packages other than `AppImage`.

**Comment by NukeManDan** [comment]
.deb via Gdebi 0.9.5.7+nmu3

Would it be possible to have other install options correctly use the update feature? :pray:

**Comment by lidel** [comment]
Sadly not feasible. 
On Linux you need to use package manager that comes with your distribution, and ping maintainer of `ipfs-desktop` package to update it to the latest `.deb`

**Comment by lidel** [comment]
Continued in https://github.com/ipfs-shipyard/ipfs-desktop/issues/1671#issuecomment-705116856

**Comment by bruno-anjos** [comment]
I think I'm experiencing a very similar error on macOS (Big Sur). I tried both installing via homebrew and using the .dmg. Both behave the same. I click the icon and nothing happens. IPFS Desktop and the daemon start running in the background but no UI. I launched via the terminal and I get this:

```2021-01-16T14:06:13.121Z info: [meta] logs can be found on /Users/my_user/Library/Application Support/IPFS Desktop
Error: ENOTDIR: not a directory, mkdir '/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/countly-sdk-nodejs/data'
    at Object.mkdirSync (fs.js:823:3)
    at Object.Countly.init (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/countly-sdk-nodejs/lib/countly.js:157:24)
    at module.exports (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/src/analytics.js:6:11)
    at run (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/src/index.js:65:11)
Error: ENOENT, node_modules/countly-sdk-nodejs/data/__cly_id.json not found in /Applications/IPFS Desktop.app/Contents/Resources/app.asar
    at createError (electron/js2c/asar.js:111:17)
    at Object.func [as openSync] (electron/js2c/asar.js:146:27)
    at Object.writeFileSync (fs.js:1265:35)
    at storeSet (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/countly-sdk-nodejs/lib/countly.js:1337:16)
    at Object.Countly.init (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/countly-sdk-nodejs/lib/countly.js:171:21)
    at module.exports (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/src/analytics.js:6:11)
    at run (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/src/index.js:65:11)
2021-01-16T14:06:14.069Z info: [web ui] window ready
2021-01-16T14:06:14.083Z info: [tray] starting
2021-01-16T14:06:14.115Z info: [tray] started
2021-01-16T14:06:14.115Z info: [ipfsd] start daemon STARTED
2021-01-16T14:06:14.304Z info: [daemon] removing api file
2021-01-16T14:06:21.911Z info: [ipfsd] start daemon FINISHED 7.795242546000052s
Checking for update
2021-01-16T14:06:21.986Z info: [ipfs on path] no action taken
2021-01-16T14:06:21.986Z info: [launch on startup] disabled
Update for version 0.13.2 is not available (latest version: 0.13.2, downgrade is disallowed).
2021-01-16T14:06:23.317Z info: [updater] update not available```

**Comment by jessicaschilling** [comment]
@bruno-anjos This looks like it may be something different. Can you please open as a separate issue and we will look more closely in our next triage? Also, any other info you can provide would be helpful, like:
- is this a brand new install or an upgrade?
- does it get as far as adding the cube-logo menu to your top system menubar?
- if you do see that menu, there is an item for opening logs. Can you attach any logs you might have?

**Comment by bruno-anjos** [comment]
@jessicaschilling of course, i only replied on this issue since it had the two first errors in common and i wasn't sure if it was really the same or not. I'll open a new issue and provide the extra info you requested. Thank you very much
