### ISSUE TITLE
ipfs-on-path experiment causes Error: spawn EPERM

### ISSUE THREAD

**Issue by TSS-LauKY** [ipfs-shipyard/ipfs-desktop#1694]
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.13.0
- **Electron Version**: 9.3.2
- **Chrome Version**: 83.0.4103.122

**Error**

```
Error: spawn EPERM
    at ChildProcess.spawn (internal/child_process.js:394:11)
    at spawn (child_process.js:549:9)
    at execFile (child_process.js:233:17)
    at module.<computed> (electron/js2c/asar.js:163:31)
    at C:\Program Files\IPFS Desktop\resources\app.asar\src\ipfs-on-path\index.js:85:5
    at new Promise (<anonymous>)
    at runWindows (C:\Program Files\IPFS Desktop\resources\app.asar\src\ipfs-on-path\index.js:84:10)
    at run (C:\Program Files\IPFS Desktop\resources\app.asar\src\ipfs-on-path\index.js:108:12)
    at firstTime (C:\Program Files\IPFS Desktop\resources\app.asar\src\ipfs-on-path\index.js:79:21)
    at module.exports (C:\Program Files\IPFS Desktop\resources\app.asar\src\ipfs-on-path\index.js:56:3)
```

**Comment by jessicaschilling** [comment]
Thanks, @TSS-LauKY! We'll investigate deeper as soon as time permits.

**Comment by lidel** [comment]
I am afraid the only fix here is to find `IPFS Desktop/config.json` and manually set:
```json
"ipfsOnPath": false,
```
We will be deprecating this feature (https://github.com/ipfs-shipyard/ipfs-desktop/pull/1768), if you want `ipfs` on your `PATH`   follow https://docs.ipfs.io/install/command-line/
