### ISSUE TITLE
go-ipfs Error: strconv.Atoi: parsing "": invalid syntax 

### ISSUE THREAD

**Issue by snakyjake1** [ipfs-shipyard/ipfs-desktop#1704]
### Error Message:
Could not connect to the IPFS API 

### Steps:
1)  New install of IPFS on Linux.
ipfs-desktop-0.13.2-linux-x86_64.AppImage

2)  Open AppImage

3)  IPFS Desktop opens.

4)  Receive the error message above.

### Combined.log

```
2020-10-24T02:54:39.880Z info: [meta] logs can be found on /home/user/.config/IPFS Desktop
2020-10-24T02:54:42.355Z info: [web ui] window ready
2020-10-24T02:54:42.356Z info: [web ui] navigate to /
2020-10-24T02:54:42.361Z info: [tray] starting
2020-10-24T02:54:42.507Z info: [tray] started
2020-10-24T02:54:42.509Z info: [ipfsd] start daemon STARTED
2020-10-24T02:54:43.461Z error: [ipfsd] start daemon Error: Initializing daemon...
go-ipfs version: 0.7.0
Repo version: 10
System version: amd64/linux
Golang version: go1.14.4
 

 Error: strconv.Atoi: parsing "": invalid syntax 

 Command failed with exit code 1: /tmp/.mount_ipfs-dkFBxmD/resources/app.asar.unpacked/node_modules/go-ipfs/go-ipfs/ipfs daemon --migrate --enable-gc --routing dhtclient
Error: strconv.Atoi: parsing "": invalid syntax
Initializing daemon...
go-ipfs version: 0.7.0
Repo version: 10
System version: amd64/linux
Golang version: go1.14.4
 


    at makeError (/tmp/.mount_ipfs-dkFBxmD/resources/app.asar/node_modules/ipfsd-ctl/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/tmp/.mount_ipfs-dkFBxmD/resources/app.asar/node_modules/ipfsd-ctl/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
2020-10-24T02:54:43.663Z info: [ipfs on path] no action taken
2020-10-24T02:54:43.675Z info: [launch on startup] disabled
2020-10-24T02:54:45.687Z info: [updater] update not available
```

### error.log

```
2020-10-24T02:54:43.461Z error: [ipfsd] start daemon Error: Initializing daemon...
go-ipfs version: 0.7.0
Repo version: 10
System version: amd64/linux
Golang version: go1.14.4
 

 Error: strconv.Atoi: parsing "": invalid syntax 

 Command failed with exit code 1: /tmp/.mount_ipfs-dkFBxmD/resources/app.asar.unpacked/node_modules/go-ipfs/go-ipfs/ipfs daemon --migrate --enable-gc --routing dhtclient
Error: strconv.Atoi: parsing "": invalid syntax
Initializing daemon...
go-ipfs version: 0.7.0
Repo version: 10
System version: amd64/linux
Golang version: go1.14.4
 


    at makeError (/tmp/.mount_ipfs-dkFBxmD/resources/app.asar/node_modules/ipfsd-ctl/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/tmp/.mount_ipfs-dkFBxmD/resources/app.asar/node_modules/ipfsd-ctl/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)

```

**Comment by jessicaschilling** [comment]
Thank you - we will look into this in our next weekly triage.

**Comment by lidel** [comment]
@snakyjake1 I was unable to reproduce (the  latest AppImage package works fine on my end).

I believe this is not a bug in IPFS Desktop, but a problem with your configuration file.
The error comes from go-ipfs:
```
Error: strconv.Atoi: parsing "": invalid syntax
```

Some ideas:

- Check if your  `~/.ipfs/config` (or `$IPFS_PATH/config` if you used custom path) exists and is a valid JSON
  - If missing, can you create a file in that directory manually? (could be permission problem)

Quick fix: 
- If you dont have any data in your repo, just remove ``~/.ipfs/` (or `$IPFS_PATH`) and retry – IPFS Desktop wil create a new `config` file and the issue should be resolved.

Feel free to reopen if none of the above helped.
