### ISSUE TITLE
Crash on system wake

### ISSUE THREAD

**Issue by DoDoENT** [ipfs-shipyard/ipfs-desktop#1706]
Please describe what you were doing when this error happened: I just waked my mac after being asleep for the night.

**Specifications**

- **OS**: darwin
- **IPFS Desktop Version**: 0.13.2
- **Electron Version**: 9.3.2
- **Chrome Version**: 83.0.4103.122

**Error**

```
TypeError: Cannot read property 'pid' of null
    at Timeout._onTimeout (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/ipfsd-ctl/src/ipfsd-daemon.js:242:101)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

**Comment by jessicaschilling** [comment]
Hi @DoDoENT -- thank you for filing this! It's a known issue and we are tracking under https://github.com/ipfs-shipyard/ipfs-desktop/issues/1702, so will close this to avoid duplication.
