### ISSUE TITLE
no known trigger event, just noticed this

### ISSUE THREAD

**Issue by ksnyde** [ipfs-shipyard/ipfs-desktop#1709]
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: darwin
- **IPFS Desktop Version**: 0.13.2
- **Electron Version**: 9.3.2
- **Chrome Version**: 83.0.4103.122

**Error**

```
Error: Command failed: npm install -g ipfs-npm
internal/modules/cjs/loader.js:968
  throw err

**Comment by ksnyde** [comment]
However, running`npm install -g ipfs-npm` from the command line I get the following:

```sh
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module '../lib/cli.js'
Require stack:
- /usr/local/lib/node_modules/npm/bin/npm-cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/local/lib/node_modules/npm/bin/npm-cli.js' ]
}
```

**Comment by jessicaschilling** [comment]
Thanks, @ksnyde - we'll take a closer look at our next triage session!

**Comment by ksnyde** [comment]
nevermind ... this appears to be related to an issue with my version of `npm`; i have fixed this now and the install did work.
