### ISSUE TITLE
No UI when launching IPFS-Desktop

### ISSUE THREAD

**Issue by bruno-anjos** [ipfs-shipyard/ipfs-desktop#1733]
- OS: macOS
 - Version of IPFS Desktop 0.13.2

**Describe the bug**
Can't start IPFS Desktop. No UI. The daemon starts running in the back so as the IPFS-Desktop process, but nothing happens. Tried both the .dmg from releases and through homebrew.

**To Reproduce**
1. Run IPFS-Desktop from the terminal

**Expected behavior**
Start the UI

**Terminal Output**
```
Error: ENOTDIR: not a directory, mkdir '/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/countly-sdk-nodejs/data'
    at Object.mkdirSync (fs.js:823:3)
    at Object.Countly.init (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/countly-sdk-nodejs/lib/countly.js:157:24)
    at module.exports (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/src/analytics.js:6:11)
    at run (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/src/index.js:65:11)
Error: ENOENT, node_modules/countly-sdk-nodejs/data/__cly_id.json not found in /Applications/IPFS Desktop.app/Contents/Resources/app.asar
    at createError (electron/js2c/asar.js:111:17)
    at Object.func [as openSync] (electron/js2c/asar.js:146:27)
    at Object.writeFileSync (fs.js:1265:35)
    at storeSet (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/countly-sdk-nodejs/lib/countly.js:1337:16)
    at Object.Countly.init (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/countly-sdk-nodejs/lib/countly.js:171:21)
    at module.exports (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/src/analytics.js:6:11)
    at run (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/src/index.js:65:11)
2021-01-16T14:06:14.069Z info: [web ui] window ready
2021-01-16T14:06:14.083Z info: [tray] starting
2021-01-16T14:06:14.115Z info: [tray] started
2021-01-16T14:06:14.115Z info: [ipfsd] start daemon STARTED
2021-01-16T14:06:14.304Z info: [daemon] removing api file
2021-01-16T14:06:21.911Z info: [ipfsd] start daemon FINISHED 7.795242546000052s
Checking for update
2021-01-16T14:06:21.986Z info: [ipfs on path] no action taken
2021-01-16T14:06:21.986Z info: [launch on startup] disabled
Update for version 0.13.2 is not available (latest version: 0.13.2, downgrade is disallowed).
2021-01-16T14:06:23.317Z info: [updater] update not available
```

**Extra logs**
error.log is empty

```
2021-01-18T21:00:43.730Z info: [meta] logs can be found on /Users/banjos/Library/Application Support/IPFS Desktop
2021-01-18T21:00:45.021Z info: [web ui] window ready
2021-01-18T21:00:45.021Z info: [tray] starting
2021-01-18T21:00:45.054Z info: [tray] started
2021-01-18T21:00:45.055Z info: [ipfsd] start daemon STARTED
2021-01-18T21:00:45.300Z info: [daemon] removing api file
2021-01-18T21:00:49.397Z info: [ipfsd] start daemon FINISHED 4.341990121006965s
2021-01-18T21:00:49.482Z info: [ipfs on path] no action taken
2021-01-18T21:00:49.482Z info: [launch on startup] disabled
2021-01-18T21:00:50.699Z info: [updater] update not available
```

**Comment by jessicaschilling** [comment]
@bruno-anjos Does the "IPFS cube" icon appear in your menu bar at the top of your screen? Just curious if you're seeing any UI at all.

**Comment by bruno-anjos** [comment]
@jessicaschilling yes it does

**Comment by bruno-anjos** [comment]
Ok so after digging a bit I figured that I can open the status or the files through the menu bar icon and that indeed opens the UI, but it seems counter intuitive that when launching the application it doesn't open the UI. I'm not sure if this is the desired behaviour.

**Comment by jessicaschilling** [comment]
@bruno-anjos FWIW, you can set Desktop to automatically open the UI on launch (I'm on a Mac, so forgive any visual differences in this screenshot):
![image](https://user-images.githubusercontent.com/1507828/105079250-65640480-5a4c-11eb-8ddc-ff8bbb2ba22d.png)
Thanks for sharing your thoughts on default behavior for this setting. We're currently evaluating a number of UI details in IPFS Desktop, so this is helpful!

**Comment by bruno-anjos** [comment]
Oh my god I'm so sorry 🤦 . I didn't understand this was not supposed to be a default config. As a user, I believe the behaviour is a bit misleading. In my case it was even worse because, like you, I'm a macOS user and I have Dozer to hide icons in my menu bar, so the IPFS icon actually didn't appear. I understand that the menu bar icon is indeed referenced in the README (multiple times) but I still believe that the expected should be to open the UI. Thank you very much for you help @jessicaschilling

**Comment by jessicaschilling** [comment]
@bruno-anjos Don't apologize! You bring up a really good point. Just opened https://github.com/ipfs-shipyard/ipfs-desktop/issues/1741 if you'd like to keep an eye on it. 😊
