### ISSUE TITLE
ERR_STREAM_DESTROYED on first launch

### ISSUE THREAD

**Issue by jayenashar** [ipfs-shipyard/ipfs-desktop#1748]
Please describe what you were doing when this error happened.
- installed ipfs-desktop from debian deb
- ran ipfs-desktop from command line
- maybe hit ctrl-z, ran `bg`, and closed the terminal?  not really sure but found this old issue so maybe i did: #1255
- ipfs desktop seemed to be running fine.  closed it with alt+f4
- saw an error message (was probably behind ipfs desktop.  was probably not from closing ipfs desktop)
- saw ipfs desktop was still running (according to companion and system tray)
- clicked to report issue
- ipfs desktop exited

**Specifications**

- **OS**: linux
- **IPFS Desktop Version**: 0.13.2
- **Electron Version**: 9.3.2
- **Chrome Version**: 83.0.4103.122

**Error**

```
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:431:19)
    at writeOrBuffer (_stream_writable.js:419:5)
    at WriteStream.Writable.write (_stream_writable.js:309:11)
    at Console.log (/opt/IPFS Desktop/resources/app.asar/node_modules/winston/lib/winston/transports/console.js:79:23)
    at Console._write (/opt/IPFS Desktop/resources/app.asar/node_modules/winston-transport/index.js:82:19)
    at doWrite (/opt/IPFS Desktop/resources/app.asar/node_modules/winston-transport/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/opt/IPFS Desktop/resources/app.asar/node_modules/winston-transport/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Console.Writable.write (/opt/IPFS Desktop/resources/app.asar/node_modules/winston-transport/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at DerivedLogger.ondata (/opt/IPFS Desktop/resources/app.asar/node_modules/winston/node_modules/readable-stream/lib/_stream_readable.js:681:20)
    at DerivedLogger.emit (events.js:228:7)
```

**Comment by jessicaschilling** [comment]
Are you able to run Desktop successfully?

**Comment by jayenashar** [comment]
yes.  it seemed to be running fine when i saw the error, and it is running fine after i started it again.  i'm not sure why reporting the error caused it to exit.

**Comment by jessicaschilling** [comment]
Strange - will discuss in our next triage, but glad you're up and running.
