### ISSUE TITLE
fail to start

### ISSUE THREAD

**Issue by Matthiasc** [ipfs-shipyard/ipfs-desktop#1761]
installing IPFS-Desktop-Setup-0.13.2 successfully and starting the app right after.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.13.2
- **Electron Version**: 9.3.2
- **Chrome Version**: 83.0.4103.122

**Error**

```
Error: spawn UNKNOWN
    at ChildProcess.spawn (internal/child_process.js:394:11)
    at spawn (child_process.js:549:9)
    at execFile (child_process.js:233:17)
    at module.<computed> (electron/js2c/asar.js:163:31)
    at C:\Users\Matthias\AppData\Local\Programs\IPFS Desktop\resources\app.asar\src\ipfs-on-path\index.js:85:5
    at new Promise (<anonymous>)
    at runWindows (C:\Users\Matthias\AppData\Local\Programs\IPFS Desktop\resources\app.asar\src\ipfs-on-path\index.js:84:10)
    at run (C:\Users\Matthias\AppData\Local\Programs\IPFS Desktop\resources\app.asar\src\ipfs-on-path\index.js:108:12)
    at firstTime (C:\Users\Matthias\AppData\Local\Programs\IPFS Desktop\resources\app.asar\src\ipfs-on-path\index.js:79:21)
    at module.exports (C:\Users\Matthias\AppData\Local\Programs\IPFS Desktop\resources\app.asar\src\ipfs-on-path\index.js:56:3)
```

**Comment by jessicaschilling** [comment]
@Matthiasc - suggesting that it may be better to take this issue to the forums at discuss.ipfs.io for more active troubleshooting, as core team members are diverted at the moment and may not be able to troubleshoot quickly. Thank you!

**Comment by lidel** [comment]
I am afraid the only fix here is to find `IPFS Desktop/config.json` and manually set:
```json
"ipfsOnPath": false,
```
We will be deprecating this feature (https://github.com/ipfs-shipyard/ipfs-desktop/pull/1768), if you want `ipfs` on your `PATH`   follow https://docs.ipfs.io/install/command-line/
