### ISSUE TITLE
ipfs not found after snap updated to latest

### ISSUE THREAD

**Issue by apunkt** [ipfs-shipyard/ipfs-desktop#1774]
- OS:  Linux Ubuntu 20.04
 - Version of IPFS Desktop 0.14.0

No connection to IPFS-API

**To Reproduce**
1. Start IPFS-Desktop

**Expected behavior**
It connects successfully to the IPFS daemin

**Additional context**
Automatic update failed and leads to permission error and missing binaries for ipfs daemong

`2021-01-25T08:28:02.610Z error: [updater] Error: ENOENT: no such file or directory, open '/snap/ipfs-desktop/23/resources/app-update.yml'
2021-01-25T08:41:00.092Z error: [ipfsd] start daemon SyntaxError: /home/andreas/snap/ipfs-desktop/23/.ipfs/config: Unexpected token ] in JSON at position 455
    at JSON.parse (<anonymous>)
    at Object.readFileSync (/snap/ipfs-desktop/23/resources/app.asar/node_modules/fs-extra/node_modules/jsonfile/index.js:52:17)
    at readConfigFile (/snap/ipfs-desktop/23/resources/app.asar/src/daemon/config.js:29:13)
    at checkPorts (/snap/ipfs-desktop/23/resources/app.asar/src/daemon/config.js:217:18)
    at module.exports (/snap/ipfs-desktop/23/resources/app.asar/src/daemon/daemon.js:74:24)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async startIpfs (/snap/ipfs-desktop/23/resources/app.asar/src/daemon/index.js:54:15)
    at async restartIpfs (/snap/ipfs-desktop/23/resources/app.asar/src/daemon/index.js:102:5)
    at async Object.restartIpfs (/snap/ipfs-desktop/23/resources/app.asar/src/daemon/index.js:33:5)
2021-01-25T10:54:30.741Z error: [updater] Error: ENOENT: no such file or directory, open '/snap/ipfs-desktop/23/resources/app-update.yml'
2021-01-26T07:59:27.512Z error: [updater] Error: ENOENT: no such file or directory, open '/snap/ipfs-desktop/23/resources/app-update.yml'
2021-01-27T08:05:30.749Z error: [updater] Error: ENOENT: no such file or directory, open '/snap/ipfs-desktop/23/resources/app-update.yml'
2021-01-28T08:59:56.701Z error: [updater] Error: ENOENT: no such file or directory, open '/snap/ipfs-desktop/23/resources/app-update.yml'
2021-01-29T07:14:28.543Z error: [updater] Error: ENOENT: no such file or directory, open '/snap/ipfs-desktop/23/resources/app-update.yml'
2021-02-01T08:21:48.005Z error: [updater] Error: ENOENT: no such file or directory, open '/snap/ipfs-desktop/23/resources/app-update.yml'
2021-02-02T08:27:47.000Z error: [updater] Error: ENOENT: no such file or directory, open '/snap/ipfs-desktop/23/resources/app-update.yml'
2021-02-03T08:07:00.874Z error: [updater] Error: ENOENT: no such file or directory, open '/snap/ipfs-desktop/23/resources/app-update.yml'
2021-02-04T08:13:44.530Z error: [updater] Error: ENOENT: no such file or directory, open '/snap/ipfs-desktop/23/resources/app-update.yml'
2021-02-05T07:58:18.895Z error: [updater] Error: ENOENT: no such file or directory, open '/snap/ipfs-desktop/23/resources/app-update.yml'
2021-02-06T13:14:15.693Z error: [updater] Error: ENOENT: no such file or directory, open '/snap/ipfs-desktop/23/resources/app-update.yml'
2021-02-07T09:56:21.439Z error: [updater] Error: ENOENT: no such file or directory, open '/snap/ipfs-desktop/23/resources/app-update.yml'
2021-02-08T09:23:13.228Z error: [updater] Error: ENOENT: no such file or directory, open '/snap/ipfs-desktop/23/resources/app-update.yml'
2021-02-09T07:49:53.021Z error: [updater] Error: ENOENT: no such file or directory, open '/snap/ipfs-desktop/23/resources/app-update.yml'
2021-02-10T07:29:53.629Z error: [updater] Error: ENOENT: no such file or directory, open '/snap/ipfs-desktop/23/resources/app-update.yml'
2021-02-11T08:12:58.546Z error: [updater] Error: ENOENT: no such file or directory, open '/snap/ipfs-desktop/23/resources/app-update.yml'
2021-02-12T07:52:04.098Z error: [updater] Error: ENOENT: no such file or directory, open '/snap/ipfs-desktop/23/resources/app-update.yml'
2021-02-15T10:15:10.124Z error: [updater] Error: ENOENT: no such file or directory, open '/snap/ipfs-desktop/23/resources/app-update.yml'
2021-02-16T07:35:27.892Z error: [updater] Error: ENOENT: no such file or directory, open '/snap/ipfs-desktop/23/resources/app-update.yml'
2021-02-16T19:35:27.217Z error: [updater] Error: ENOENT: no such file or directory, open '/snap/ipfs-desktop/23/resources/app-update.yml'
2021-02-17T07:39:43.658Z error: [updater] Error: ENOENT: no such file or directory, open '/snap/ipfs-desktop/23/resources/app-update.yml'
2021-02-18T09:18:35.667Z error: [updater] Error: ENOENT: no such file or directory, open '/snap/ipfs-desktop/23/resources/app-update.yml'
2021-02-19T07:55:35.168Z error: [updater] Error: ENOENT: no such file or directory, open '/snap/ipfs-desktop/23/resources/app-update.yml'
2021-02-22T07:51:52.204Z error: [updater] Error: ENOENT: no such file or directory, open '/snap/ipfs-desktop/23/resources/app-update.yml'
2021-02-23T07:38:01.873Z error: [updater] Error: ENOENT: no such file or directory, open '/snap/ipfs-desktop/23/resources/app-update.yml'
2021-02-24T07:40:21.391Z error: [updater] Error: ENOENT: no such file or directory, open '/snap/ipfs-desktop/23/resources/app-update.yml'
2021-02-25T07:29:13.306Z error: [ipfsd] start daemon Error: EACCES: permission denied, unlink '/home/andreas/snap/ipfs-desktop/23/.ipfs/api'
    at Object.unlinkSync (fs.js:1140:3)
    at Object.rimrafSync [as removeSync] (/snap/ipfs-desktop/24/resources/app.asar/node_modules/fs-extra/lib/remove/rimraf.js:245:15)
    at rmApiFile (/snap/ipfs-desktop/24/resources/app.asar/src/daemon/config.js:21:13)
    at module.exports (/snap/ipfs-desktop/24/resources/app.asar/src/daemon/daemon.js:92:5)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async startIpfs (/snap/ipfs-desktop/24/resources/app.asar/src/daemon/index.js:54:15)
    at async module.exports (/snap/ipfs-desktop/24/resources/app.asar/src/daemon/index.js:116:3)
    at async run (/snap/ipfs-desktop/24/resources/app.asar/src/index.js:74:5)
2021-02-25T07:29:42.424Z error: [ipfsd] start daemon Error: EACCES: permission denied, unlink '/home/andreas/snap/ipfs-desktop/23/.ipfs/api'
    at Object.unlinkSync (fs.js:1140:3)
    at Object.rimrafSync [as removeSync] (/snap/ipfs-desktop/24/resources/app.asar/node_modules/fs-extra/lib/remove/rimraf.js:245:15)
    at rmApiFile (/snap/ipfs-desktop/24/resources/app.asar/src/daemon/config.js:21:13)
    at module.exports (/snap/ipfs-desktop/24/resources/app.asar/src/daemon/daemon.js:92:5)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async startIpfs (/snap/ipfs-desktop/24/resources/app.asar/src/daemon/index.js:54:15)
    at async restartIpfs (/snap/ipfs-desktop/24/resources/app.asar/src/daemon/index.js:102:5)
    at async Object.restartIpfs (/snap/ipfs-desktop/24/resources/app.asar/src/daemon/index.js:33:5)
2021-02-25T07:30:43.577Z error: [ipfsd] start daemon Error: EACCES: permission denied, unlink '/home/andreas/snap/ipfs-desktop/23/.ipfs/api'
    at Object.unlinkSync (fs.js:1140:3)
    at Object.rimrafSync [as removeSync] (/snap/ipfs-desktop/24/resources/app.asar/node_modules/fs-extra/lib/remove/rimraf.js:245:15)
    at rmApiFile (/snap/ipfs-desktop/24/resources/app.asar/src/daemon/config.js:21:13)
    at module.exports (/snap/ipfs-desktop/24/resources/app.asar/src/daemon/daemon.js:92:5)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async startIpfs (/snap/ipfs-desktop/24/resources/app.asar/src/daemon/index.js:54:15)
    at async restartIpfs (/snap/ipfs-desktop/24/resources/app.asar/src/daemon/index.js:102:5)
    at async Object.restartIpfs (/snap/ipfs-desktop/24/resources/app.asar/src/daemon/index.js:33:5)
2021-02-25T07:30:55.872Z error: [ipfsd] start daemon Error: EACCES: permission denied, unlink '/home/andreas/snap/ipfs-desktop/23/.ipfs/api'
    at Object.unlinkSync (fs.js:1140:3)
    at Object.rimrafSync [as removeSync] (/snap/ipfs-desktop/24/resources/app.asar/node_modules/fs-extra/lib/remove/rimraf.js:245:15)
    at rmApiFile (/snap/ipfs-desktop/24/resources/app.asar/src/daemon/config.js:21:13)
    at module.exports (/snap/ipfs-desktop/24/resources/app.asar/src/daemon/daemon.js:92:5)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async startIpfs (/snap/ipfs-desktop/24/resources/app.asar/src/daemon/index.js:54:15)
    at async module.exports (/snap/ipfs-desktop/24/resources/app.asar/src/daemon/index.js:116:3)
    at async run (/snap/ipfs-desktop/24/resources/app.asar/src/index.js:74:5)`

**Comment by apunkt** [comment]
Reverting back to 0.13.2 with _snap revert ipfs-desktop_ as a workaround until 0.14 is fixed

**Comment by lidel** [comment]
Thank you @apunkt, do you know if anything changed recently in Snap ecosystem?
Our config did not change since 0.13.2:

https://github.com/ipfs-shipyard/ipfs-desktop/blob/0f49825c78c9f4d288d6ca51b9586c39da878789/electron-builder.yml#L66-L74

**Comment by djamayaofficial** [comment]
For what it's worth, I can confirm this issue with the snap package exists on Manjaro Linux as well. A friend and I both had the same exact issue when the update dropped. 

I can also confirm reverting fixes it, _AND_ also, **the Appimage appears to work flawlessly** though with the most recent version so that's also a workaround. I'm not sure what the difference is, but appears to be specifically the most recent snap update.

With that said, as I write this about 4 days after experiencing the issue, I just attempted to run the snap again, and It worked as expected. Not sure if this is fixed for others yet or not, but seems to be working now at least on my machine with the snap package. 

Hope this additional info/report helps.

**Comment by apunkt** [comment]
I am not aware of changes in snap ecosystem. I just experience this problem with this snap on two different systems, both systems run unattended-upgrades.
I also can confirm, that manually upgrading the snap to 0.14.0 will make it work, but also it will stop working again after some time (2-4h) and only reverting it back to 0.13.2 will make it work again.
0.13.2 will however show AGENT: go-ipfs v0.7.0 UI v2.11.4 which seems wrong running 0.13.2
0.13.2 will now also crash randomly after 2-4h, but can be restarted.

I am running another system with similar config, but this is running plain ipfs snap 0.8.0-ce693d7e8.
This also stopped, but restart did some repo conversion and this is running stable since.

**Comment by apunkt** [comment]
Trying to add a file in reverted snap (013.2) through ipfs-desktop or even through API will crash the snap without any line in the error log.
Updating to snap 0.14 and adding a file through ipfs-desktop or via API will make the API inaccessible:

'EACCES: permission denied, unlink '/home/andreas/snap/ipfs-desktop/23/.ipfs/api'

No way to fix this other than reverting back.

**Comment by lidel** [comment]
Snap for v0.15.1 just got published to https://snapcraft.io/ipfs-desktop  thanks to https://github.com/ipfs/ipfs-desktop/pull/1845 

Anyone with spare time to re-test this? (there is a chance that the latest tooling made `EACCES: permission denied` go away).

**Comment by lidel** [comment]
Assuming  fixed in v0.16.3
