### ISSUE TITLE
Cannot add folder more than a single level deep

### ISSUE THREAD

**Issue by olizilla** [ipfs-shipyard/ipfs-desktop#613]
Adding a folder with a sub folder with a file 

```
parent
└── sub
    └── two.txt
```

leaves me with the upload progress bar. I can still click around the app. It feels like the upload is in progess, just taking a really really long time, like > 10 minutes to upload a 200 byte file that happens to be 2 dirs deep.

**Comment by hacdias** [comment]
Can't reproduce. Could you see if updating the deps resolves this on your PC (#615)?

**Comment by olizilla** [comment]
Still a problem. I'm macOS 10.12.6

**Comment by lidel** [comment]
Same problem under Debian Linux:

- uploading flat directory works fine (`screenshots`)
- uploading flat directory fails, progressbar spinner is aminating but nothing happens.
  I was able to get some debug info tho, see below:

```
DEBUG='desktop' ipfs-desktop
(..)
  desktop Uploading files { files: [ '/home/lidel/tmp/screnshots' ] } +28s
  desktop Uploading files { files: [ '/home/lidel/tmp/ipfs_companion-2.2.0-ipfs-dialog' ] } +19s
  desktop Error: file does not exist
  desktop     at parseError (/usr/lib/ipfs-desktop/resources/app/node_modules/ipfs-api/src/utils/send-request.js:16:17)
  desktop     at ClientRequest.<anonymous> (/usr/lib/ipfs-desktop/resources/app/node_modules/ipfs-api/src/utils/send-request.js:39:14)
  desktop     at Object.onceWrapper (events.js:316:30)
  desktop     at emitOne (events.js:115:13)
  desktop     at ClientRequest.emit (events.js:210:7)
  desktop     at HTTPParser.parserOnIncomingClient (_http_client.js:565:21)
  desktop     at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
  desktop     at Socket.socketOnData (_http_client.js:454:20)
  desktop     at emitOne (events.js:115:13)
  desktop     at Socket.emit (events.js:210:7) +236ms
```
