### ISSUE TITLE
property 'statusCode' of undefined:  in npm install 

### ISSUE THREAD

**Issue by rogerlzp** [ipfs-shipyard/ipfs-desktop#643]
Hey, 

There is an error happened when install it in my Env.
Env details:
MAC  High Sierra
npm: n6.1.0
node: v10.2.1

There error log:
Downloading https://dist.ipfs.io/go-ipfs/v0.4.15/go-ipfs_v0.4.15_darwin-amd64.tar.gz
/Users/zhengpingli/work/ipfs/ipfs-desktop/ipfs-desktop/node_modules/go-ipfs-dep/src/index.js:102
      if (res.statusCode !== 200) {
              ^

TypeError: Cannot read property 'statusCode' of undefined
    at Request.request.get [as _callback] (/Users/zhengpingli/work/ipfs/ipfs-desktop/ipfs-desktop/node_modules/go-ipfs-dep/src/index.js:102:15)
    at self.callback (/Users/zhengpingli/work/ipfs/ipfs-desktop/ipfs-desktop/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.onRequestError (/Users/zhengpingli/work/ipfs/ipfs-desktop/ipfs-desktop/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:182:13)
    at TLSSocket.socketErrorListener (_http_client.js:382:9)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! go-ipfs-dep@0.4.15 install: `node src/bin.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the go-ipfs-dep@0.4.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zhengpingli/.npm/_logs/2018-06-04T05_26_10_250Z-debug.log

Looks like some error happened in the js file.
Anyone who met before can give a tip on how to resolve this?

**Comment by hacdias** [comment]
Could you try the [latest release](https://github.com/ipfs-shipyard/ipfs-desktop/releases) and see if there is any error now?

**Comment by hacdias** [comment]
Closing as unrelated to the newer version.
