### ISSUE TITLE
Drag and drop file into menubar crashes application

### ISSUE THREAD

**Issue by craigbranscom** [ipfs-shipyard/ipfs-desktop#673]
I tried dragging and dropping a .txt file into the menubar application. The GUI immediately went completely black and is unresponsive. The error messages are hidden by the black screen as well.

```Failed to compile /Users/hotmdev5/Desktop/ratemtests.txt: Asked for /Users/hotmdev5/Desktop/ratemtests.txt but it was not precompiled!
Error: Asked for /Users/hotmdev5/Desktop/ratemtests.txt but it was not precompiled!
    at FileChangedCache.getCacheEntryForPath (/Applications/IPFS Desktop.app/Contents/Resources/app/node_modules/electron-compile/lib/file-change-cache.js:218:15)
    at /Applications/IPFS Desktop.app/Contents/Resources/app/node_modules/electron-compile/lib/file-change-cache.js:127:41
    at Generator.next (<anonymous>)
    at step (/Applications/IPFS Desktop.app/Contents/Resources/app/node_modules/electron-compile/lib/file-change-cache.js:27:191)
    at /Applications/IPFS Desktop.app/Contents/Resources/app/node_modules/electron-compile/lib/file-change-cache.js:27:437
    at new Promise (<anonymous>)
    at /Applications/IPFS Desktop.app/Contents/Resources/app/node_modules/electron-compile/lib/file-change-cache.js:27:99
    at FileChangedCache.getHashForPath (/Applications/IPFS Desktop.app/Contents/Resources/app/node_modules/electron-compile/lib/file-change-cache.js:177:7)
    at /Applications/IPFS Desktop.app/Contents/Resources/app/node_modules/electron-compile/lib/compiler-host.js:298:51
    at Generator.next (<anonymous>)```

**Comment by hacdias** [comment]
Closing as unrelated to the newer version.

**Comment by daviddias** [comment]
@hacdias drag and drop is not working for me on 0.6.0 pre-release. Was that feature removed?

**Comment by hacdias** [comment]
@daviddias yes, it was removed. But the steps to drag-n-drop are the same: open menubar -> Click on Files -> drop to the files window. The only difference is that the Files window is part of Web UI, hence separated from the main menubar window.
