### ISSUE TITLE
Missing support for external daemon already running

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-desktop#688]
> Issue found while testing "The PR" @  https://github.com/ipfs-shipyard/ipfs-desktop/pull/662#issuecomment-437576673

## Bug

ipfs-desktop fails to start when API port is already in use   (no error, no UI is shown, it just hangs) 

<details>
  <summary>Click to expand debug log</summary>

```console
$ DEBUG='*' npm run start
(...)
  ipfsd-ctl:daemon:stdout Initializing daemon...
  ipfsd-ctl:daemon:stdout go-ipfs version: 0.4.18-
  ipfsd-ctl:daemon:stdout Repo version: 7
  ipfsd-ctl:daemon:stdout System version: amd64/linux
  ipfsd-ctl:daemon:stdout Golang version: go1.11.1 +0ms
  ipfsd-ctl:daemon:stdout Swarm listening on /ip6/::1/tcp/4001
  ipfsd-ctl:daemon:stdout Swarm listening on /p2p-circuit +2s
  ipfsd-ctl:daemon:stdout Swarm announcing /ip6/::1/tcp/4001 +1ms
  ipfsd-ctl:daemon:stderr Error: serveHTTPApi: manet.Listen(/ip4/127.0.0.1/tcp/5001) failed: listen tcp4 127.0.0.1:5001: bind: address already in use +0ms
  ipfsd-ctl:daemon:stdout Received interrupt signal, shutting down...
  ipfsd-ctl:daemon:stdout (Hit ctrl-c again to force-shutdown the daemon.) +51ms
(node:14832) UnhandledPromiseRejectionWarning: Error: Command failed: /home/lidel/project/ipfs-desktop/node_modules/go-ipfs-dep/go-ipfs/ipfs daemon
Error: serveHTTPApi: manet.Listen(/ip4/127.0.0.1/tcp/5001) failed: listen tcp4 127.0.0.1:5001: bind: address already in use

Initializing daemon...
go-ipfs version: 0.4.18-
Repo version: 7
System version: amd64/linux
Golang version: go1.11.1
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit
Swarm announcing /ip6/::1/tcp/4001
Received interrupt signal, shutting down...
(Hit ctrl-c again to force-shutdown the daemon.)

    at makeError (/home/lidel/project/ipfs-desktop/node_modules/ipfsd-ctl/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/home/lidel/project/ipfs-desktop/node_modules/ipfsd-ctl/node_modules/execa/index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:14832) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:14832) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

</details>

**Comment by NatoBoram** [comment]
It's also missing support for `$IPFS_PATH` when creating its node via the snap package in [untagged-ceae97a7f71f0f172c01](https://github.com/ipfs-shipyard/ipfs-desktop/releases/tag/untagged-ceae97a7f71f0f172c01).
