### ISSUE TITLE
build error in windows environment(win10/win7) 

### ISSUE THREAD

**Issue by HelloWorldJackLiu** [ipfs-shipyard/ipfs-desktop#703]
excuse me, i got a problem. 
when i perform npm start,it seems the problem is 
 Error: failed to get config value:"API.HTTPHeaders key has no attributes"
 the following is the whole message: 
===================================================
C:\Users\jackliu\ipfs-desktop>npm start

> ipfs-desktop@1.0.0 start C:\Users\jackliu\ipfs-desktop
> cross-env NODE_ENV=development electron -r @babel/register src/index.js
superagent: Enable experimental feature http2
2018-11-22T07:43:46.895Z info: Logger set up. Logs can be found on C:\Users\jackliu\AppData\Roaming\Electron
(node:6376) ExperimentalWarning: The http2 module is an experimental API.
2018-11-22T07:43:47.068Z info: Cleaning repo.lock and api files
(node:6376) UnhandledPromiseRejectionWarning: Error: failed to get config value:
"API.HTTPHeaders key has no attributes"
    at parseError (C:\Users\jackliu\ipfs-desktop\node_modules\ipfs-api\src\utils\
send-request.js:17:17)
    at ClientRequest.<anonymous> (C:\Users\jackliu\ipfs-desktop\node_modules\ipfs
-api\src\utils\send-request.js:47:14)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:182:13)
    at HTTPParser.parserOnIncomingClient (_http_client.js:546:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at Socket.socketOnData (_http_client.js:432:20)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
(node:6376) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection
id: 1)
(node:6376) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
Node.js process with a non-zero exit code.
===================================================
nodejs version: 10.13.0
npm version: 6.4.1
i've already installed" windows-build-tools using npm install --global --production windows-build-tools "
Is there any reason for this?

**Comment by lidel** [comment]
This should be fixed by https://github.com/ipfs-shipyard/ipfs-desktop/pull/709 – try the latest `master` :)

**Comment by HelloWorldJackLiu** [comment]
@lidel 
OK~Thanks!! :)
