### ISSUE TITLE
Improve UX when API port is already in use

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-desktop#739]
### Current State

If I already have something running on port `:5001` ipfs-desktop fails to start and generic error is displayed (3b7c7812fa4ff717c4e16317ae6deefb5242c7e1):

![2018-12-09--19-53-56](https://user-images.githubusercontent.com/157609/49701399-45ff1a00-fbec-11e8-9461-db9b792a6acd.png)

Actual error can be found in logs:
```
Error: Command failed: /home/lidel/project/ipfs-desktop/node_modules/go-ipfs-dep/go-ipfs/ipfs daemon --migrate=true --routing=dhtclient
Error: serveHTTPApi: manet.Listen(/ip4/127.0.0.1/tcp/5001) failed: listen tcp4 127.0.0.1:5001: bind: address already in use

Initializing daemon...
go-ipfs version: 0.4.18-
Repo version: 7
System version: amd64/linux
Golang version: go1.11.1
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit
Swarm announcing /ip6/::1/tcp/4001
Received interrupt signal, shutting down...
(Hit ctrl-c again to force-shutdown the daemon.)

    at makeError (/home/lidel/project/ipfs-desktop/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/home/lidel/project/ipfs-desktop/node_modules/execa/index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

### Proposed Improvements

IPFS Desktop should detect `Error: serveHTTPApi: [...] bind: address already in use` and

- at minimum: display `failed: listen tcp4 127.0.0.1:5001: bind: address already in use` 
- nice to have: display UI for changing API port and retrying
- extra: find a free port and  display it in the UI so user does not guess what is safe to use

**Comment by lidel** [comment]
Continued in https://github.com/ipfs-shipyard/ipfs-desktop/issues/912
