### ISSUE TITLE
App won't start

### ISSUE THREAD

**Issue by chrisdbarnett** [ipfs-shipyard/ipfs-desktop#777]
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: linux
- **IPFS Desktop Version**: 4.0.0
- **Electron Version**: 4.0.0
- **Chrome Version**: 69.0.3497.106

**Error**

```
Error: Command failed: /home/chrisdbarnett/ipfs-desktop/node_modules/go-ipfs-dep/go-ipfs/ipfs daemon --migrate=true --routing=dhtclient
Error: serveHTTPApi: manet.Listen(/ip4/127.0.0.1/tcp/5001) failed: listen tcp4 127.0.0.1:5001: bind: address already in use

Initializing daemon...
go-ipfs version: 0.4.18-
Repo version: 7
System version: amd64/linux
Golang version: go1.11.1
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/172.17.0.1/tcp/4001
Swarm listening on /ip4/172.18.0.1/tcp/4001
Swarm listening on /ip4/172.19.0.1/tcp/4001
Swarm listening on /ip4/172.21.0.1/tcp/4001
Swarm listening on /ip4/192.168.0.5/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/172.17.0.1/tcp/4001
Swarm announcing /ip4/172.18.0.1/tcp/4001
Swarm announcing /ip4/172.19.0.1/tcp/4001
Swarm announcing /ip4/172.21.0.1/tcp/4001
Swarm announcing /ip4/192.168.0.5/tcp/4001
Swarm announcing /ip4/86.3.159.171/tcp/36018
Swarm announcing /ip6/::1/tcp/4001
Received interrupt signal, shutting down...
(Hit ctrl-c again to force-shutdown the daemon.)

    at makeError (/home/chrisdbarnett/ipfs-desktop/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/home/chrisdbarnett/ipfs-desktop/node_modules/execa/index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by chrisdbarnett** [comment]
Never mind. Sorted. Quite obvious, already had node running in background hogging port 5001

**Comment by chrisdbarnett** [comment]
Never mind. Sorted. Quite obvious, already had node running in background hogging port 5001
