### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by billgavin** [ipfs-shipyard/ipfs-desktop#786]
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.6.1
- **Electron Version**: 4.0.0
- **Chrome Version**: 69.0.3497.106

**Error**

```
Error: net::ERR_CONNECTION_TIMED_OUT
    at GitHubProvider.getLatestVersion (C:\Program Files\IPFS Desktop\resources\app.asar\node_modules\electron-updater\src\providers\GitHubProvider.ts:39:25)
    at C:\Program Files\IPFS Desktop\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:347:26
    at Generator.next (<anonymous>)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
From previous event:
    at NsisUpdater.getUpdateInfoAndProvider (C:\Program Files\IPFS Desktop\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:336:43)
    at C:\Program Files\IPFS Desktop\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:363:31
    at Generator.next (<anonymous>)
From previous event:
    at NsisUpdater.doCheckForUpdates (C:\Program Files\IPFS Desktop\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:360:34)
    at NsisUpdater.checkForUpdates (C:\Program Files\IPFS Desktop\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:220:35)
    at NsisUpdater.checkForUpdatesAndNotify (C:\Program Files\IPFS Desktop\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:249:41)
    at _callee$ (C:\Program Files\IPFS Desktop\resources\app.asar\out\index.js:52:44)
    at tryCatch (C:\Program Files\IPFS Desktop\resources\app.asar\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (C:\Program Files\IPFS Desktop\resources\app.asar\node_modules\regenerator-runtime\runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Program Files\IPFS Desktop\resources\app.asar\node_modules\regenerator-runtime\runtime.js:114:21)
    at asyncGeneratorStep (C:\Program Files\IPFS Desktop\resources\app.asar\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Program Files\IPFS Desktop\resources\app.asar\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Program Files\IPFS Desktop\resources\app.asar\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Program Files\IPFS Desktop\resources\app.asar\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at _checkUpdates (C:\Program Files\IPFS Desktop\resources\app.asar\out\index.js:64:24)
    at checkUpdates (C:\Program Files\IPFS Desktop\resources\app.asar\out\index.js:38:24)
    at _callee2$ (C:\Program Files\IPFS Desktop\resources\app.asar\out\index.js:96:13)
    at tryCatch (C:\Program Files\IPFS Desktop\resources\app.asar\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (C:\Program Files\IPFS Desktop\resources\app.asar\node_modules\regenerator-runtime\runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Program Files\IPFS Desktop\resources\app.asar\node_modules\regenerator-runtime\runtime.js:114:21)
    at asyncGeneratorStep (C:\Program Files\IPFS Desktop\resources\app.asar\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
```

**Comment by hacdias** [comment]
@billgavin that issue was fixed in the latest versions. Please install a newer one! 😃
