### ISSUE TITLE
Error when auto-updating IPFS-Desktop installed from Scoop

### ISSUE THREAD

**Issue by NatoBoram** [ipfs-shipyard/ipfs-desktop#814]
I rebooted my computer and IPFS-Desktop greeted me with an error message.

IPFS-Desktop was installed using [Scoop](https://scoop.sh).

**Specifications**

- **OS :** win32
- **IPFS Desktop Version :** 0.6.1
- **Electron Version :** 4.0.0
- **Chrome Version :** 69.0.3497.106

**Error**

```
Error: net::ERR_NAME_NOT_RESOLVED
    at GitHubProvider.getLatestVersion (D:\Scoop\apps\ipfs-desktop\0.6.1\resources\app.asar\node_modules\electron-updater\src\providers\GitHubProvider.ts:39:25)
    at D:\Scoop\apps\ipfs-desktop\0.6.1\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:347:26
    at Generator.next (<anonymous>)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
From previous event:
    at NsisUpdater.getUpdateInfoAndProvider (D:\Scoop\apps\ipfs-desktop\0.6.1\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:336:43)
    at D:\Scoop\apps\ipfs-desktop\0.6.1\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:363:31
    at Generator.next (<anonymous>)
From previous event:
    at NsisUpdater.doCheckForUpdates (D:\Scoop\apps\ipfs-desktop\0.6.1\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:360:34)
    at NsisUpdater.checkForUpdates (D:\Scoop\apps\ipfs-desktop\0.6.1\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:220:35)
    at NsisUpdater.checkForUpdatesAndNotify (D:\Scoop\apps\ipfs-desktop\0.6.1\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:249:41)
    at _callee$ (D:\Scoop\apps\ipfs-desktop\0.6.1\resources\app.asar\out\index.js:52:44)
    at tryCatch (D:\Scoop\apps\ipfs-desktop\0.6.1\resources\app.asar\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (D:\Scoop\apps\ipfs-desktop\0.6.1\resources\app.asar\node_modules\regenerator-runtime\runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (D:\Scoop\apps\ipfs-desktop\0.6.1\resources\app.asar\node_modules\regenerator-runtime\runtime.js:114:21)
    at asyncGeneratorStep (D:\Scoop\apps\ipfs-desktop\0.6.1\resources\app.asar\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Scoop\apps\ipfs-desktop\0.6.1\resources\app.asar\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at D:\Scoop\apps\ipfs-desktop\0.6.1\resources\app.asar\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at D:\Scoop\apps\ipfs-desktop\0.6.1\resources\app.asar\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at _checkUpdates (D:\Scoop\apps\ipfs-desktop\0.6.1\resources\app.asar\out\index.js:64:24)
    at checkUpdates (D:\Scoop\apps\ipfs-desktop\0.6.1\resources\app.asar\out\index.js:38:24)
    at _callee2$ (D:\Scoop\apps\ipfs-desktop\0.6.1\resources\app.asar\out\index.js:96:13)
    at tryCatch (D:\Scoop\apps\ipfs-desktop\0.6.1\resources\app.asar\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (D:\Scoop\apps\ipfs-desktop\0.6.1\resources\app.asar\node_modules\regenerator-runtime\runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (D:\Scoop\apps\ipfs-desktop\0.6.1\resources\app.asar\node_modules\regenerator-runtime\runtime.js:114:21)
    at asyncGeneratorStep (D:\Scoop\apps\ipfs-desktop\0.6.1\resources\app.asar\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
```

**Comment by hacdias** [comment]
Hey @NatoBoram! Sorry for hearing that. Just a question: were you connected to the Internet when that happened?

**Comment by hacdias** [comment]
@NatoBoram thanks for the info. On the next version, hopefully, IPFS Desktop won't break with this kind of errors.
