### ISSUE TITLE
When offline, trying to launch desktop creates an error

### ISSUE THREAD

**Issue by momack2** [ipfs-shipyard/ipfs-desktop#834]
I turned off wifi and tried to start ipfs desktop - both times it gave me a "this application quit due to an error, do you want to restart?" After I turned wifi back on, it started just fine.

**Specifications**

- **OS**: darwin
- **IPFS Desktop Version**: 0.6.0
- **Electron Version**: 3.0.13
- **Chrome Version**: 66.0.3359.181

**Error**

```
Error: net::ERR_INTERNET_DISCONNECTED
    at GitHubProvider.getLatestVersion (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/electron-updater/src/providers/GitHubProvider.ts:39:25)
    at /Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:347:26
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at MacUpdater.getUpdateInfoAndProvider (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:336:43)
    at /Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:363:31
    at Generator.next (<anonymous>)
From previous event:
    at MacUpdater.doCheckForUpdates (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:360:34)
    at MacUpdater.checkForUpdates (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:220:35)
    at MacUpdater.checkForUpdatesAndNotify (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:249:41)
    at _callee$ (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/out/index.js:52:44)
    at tryCatch (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:114:21)
    at asyncGeneratorStep (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at /Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at /Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12
    at _checkUpdates (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/out/index.js:64:24)
    at checkUpdates (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/out/index.js:38:24)
    at _callee2$ (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/out/index.js:96:13)
    at tryCatch (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:114:21)
    at asyncGeneratorStep (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
```

**Comment by olizilla** [comment]
Oh that sucks. That's our auto-update mechanism checking to see if there is a new release. I think it should be a simple fix to just ignore errors where we can't reach github.

**Comment by olizilla** [comment]
@hacdias can you check it out. We should fix this before releasing.

**Comment by hacdias** [comment]
Hey @momack2! I see you're still using 0.6.0. We have fixed this error already. Could you try installing the [latest version](https://github.com/ipfs-shipyard/ipfs-desktop/releases), please? 😄

**Comment by olizilla** [comment]
Oh great news @hacdias !

**Comment by momack2** [comment]
Thanks! Seemed to fix it. =]
